### ISSUE TITLE
[FEATURE] Sphinx plugin

### ISSUE THREAD

**Issue by rgreinho** [tiangolo/typer#100]
### Is your feature request related to a problem

I want to be able to integrate the generation of the CLI documentation to the documentation I build with Sphinx.

### The solution you would like

A sphinx plugin seems like the perfect candidate. Something like [sphinx-click](https://pypi.org/project/sphinx-click/).

### Describe alternatives you've considered

The workaround I am using is to modify the `Makefile` provided by Sphinx to generate the Typer documentation with [typer-cli](https://typer.tiangolo.com/typer-cli/#generate-docs-with-typer-cli):

```Makefile
DETAILED_USAGE_PAGE = source/usage.md

%: Makefile
    echo "# Detailed usage" > "$(DETAILED_USAGE_PAGE)"
    typer $(shell git rev-parse --show-toplevel)/tfpy/main.py utils docs --name tfpy | tail -n +2 >> "$(DETAILED_USAGE_PAGE)"
    @$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

Here is the [actual file](https://github.com/rgreinho/tfpy/blob/master/docs/Makefile).

### Additional context

Here is the project I am using Typer with: [tfpy](https://github.com/rgreinho/tfpy). And its [documentation](https://rgreinho.github.io/tfpy/).

**Comment by tiangolo** [comment]
So, this would actually be a feature request for [Typer CLI](https://github.com/tiangolo/typer-cli) not for Typer itself.

I'm personally not a fan of Sphinx and reStructuredText :sweat_smile: 

But maybe if supporting it is not very complex and can be done in a similar way as Markdown I would probably accept PRs there.

**Comment by rgreinho** [comment]
It does not need to be reStructuredText, markdown works just fine with Sphinx 👍

**Comment by tiangolo** [comment]
Ah, cool! Although in that case, I'm not sure I understand what would be the feature request :thinking:

**Comment by rgreinho** [comment]
I was thinking of the following:

1. It would be nice if I could avoid the workaround, where I have to discard the page title.
2. It would be nice if simply by running the sphinx command, the documentation would be built. No need for the Makefile workaround. The behavior would be similar to `sphinx-click`.

**Comment by tiangolo** [comment]
I see. Well, discarding the title page could be done in Typer CLI, I would probably take a PR with a `--include-title` flag that defaults to `True` and can be disabled if that helps.

Having it integrated with Sphinx like `sphinx-click` would probably require an external plugin. Or an extension to `sphinx-click`. I'm not sure how that would work, but it would probably work better as an external project.

**Comment by xeor** [comment]
Did anyone do any work on this? I'm in the process of starting a new cli-project, and it would be very nice to have some automated docs, like `sphinx-click`..
