### ISSUE TITLE
[QUESTION] Question re: `Testing` docs—Is an empty __init__.py required?

### ISSUE THREAD

**Issue by paxcodes** [tiangolo/typer#105]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [n/a] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [n/a] I already searched in Google "How to X in Click" and didn't find any information.

### Description

I'm relatively new to Python so I want to ask something about the docs. In docs about [Testing](https://typer.tiangolo.com/tutorial/testing), it says

>  And the directory also has an empty app/__init__.py file. So, the app is a "Python package".

It makes it sound like an empty `__init__.py` *should* be there when I've been reading that this is [no longer required](https://stackoverflow.com/a/48804718/11006952) for Python packages since Python 3.3+ and I'm not planning to [distribute my typer app](https://dev.to/methane/don-t-omit-init-py-3hga). 

### The Question
What am I missing? Is an empty `__init__.py` indeed required to be able to test my typer app?

Thanks for the awesome package,
Also a FastAPI User

**Comment by tiangolo** [comment]
I'm not familiar with that PEP, but reading the blog post you linked from a Python core developer, I would keep them :shrug: 

I'm not really sure in which cases it could be ok to omit that file, but also editors will probably have a hard time providing you their features for a package without those files.

So, I would just keep it :heavy_check_mark:

**Comment by paxcodes** [comment]
Thanks for the response @tiangolo!
