### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Kludex** [tiangolo/typer#109]
### Description

Is it possible to add a new field to the `OAuth2PasswordRequestForm`?

### Additional context

I need to add a new optional field called `new_password` in the following `Request Body`:
![WhatsApp Image 2020-05-26 at 19 26 29](https://user-images.githubusercontent.com/7353520/82931205-d5d28880-9f86-11ea-9a4b-05623df9b63a.jpeg)

What I was trying to do:
```
class LoginForm(OAuth2PasswordRequestForm):
    def __init__(self, new_password: str = Form(None)):
        super().__init__()
        self.new_password = new_password
```
But it overwrites what is there and just show the `new_password`:
![image](https://user-images.githubusercontent.com/7353520/82931751-aec88680-9f87-11ea-962b-8cf513a88fe3.png)

**Comment by tiangolo** [comment]
I guess you intended to ask this in FastAPI... :smile: thanks for closing it here :+1:
