### ISSUE TITLE
[FEATURE] Handling Mutliple Variable Length Arguments

### ISSUE THREAD

**Issue by rmorshea** [tiangolo/typer#110]
I'm not familiar with the internals of `typer` and whether this is feasible, but it would be nice if it were possible to implement a command like the following:

```python
from typing import Optional, List

import typer

app = typer.Typer()


@app.command()
def main(first_list: List[str], option: bool = False, second_list: List[str] = ()):
    print(first_list, second_list)
```

Where the expected behavior is:

```bash
$ python main.py a b c --option d e f
('a', 'b', 'c') ('d', 'e', 'f')
$ python main.py a b c d e f --option
('a', 'b', 'c', 'd', 'e', 'f') ()
$ python main.py a b c d e f
('a', 'b', 'c', 'd', 'e', 'f') ()
```

However the actual behavior in this case does not adhere to the above:

```bash
$ python main.py a b c --option d e f
('a', 'b', 'c', 'd', 'e', 'f') True ()
```

This can presently be achieved in `argparse` quite concisely:

```python
import argparse

def main():
    cli = argparse.ArgumentParser()
    cli.add_argument(
        "first_list", nargs="*", type=str,
    )
    cli.add_argument(
        "--option", nargs="*", type=str, default=[],
    )
    args = cli.parse_args()
    print(args.first_list, args.option)
```

**Comment by tiangolo** [comment]
Thanks for the help here @IamCathal ! :rocket: :cake: 

Yeah, it's a constraint in Click: https://click.palletsprojects.com/en/7.x/options/#multi-value-options

> For options, only a fixed number of arguments is supported.

To declare a fixed number of arguments for a CLI option you can use tuples: https://typer.tiangolo.com/tutorial/multiple-values/options-with-multiple-values/

**Comment by alsimoneau** [comment]
I feel like this issue isn't solved.

The original post mention that this would be an appreciated feature that is supported by others.
Stating that it is not supported is in no way an answer as that is the point of the issue.

I also have a use case where that feature would be useful.
When passing wildcards to the option, bash automatically expands them. This makes the use of the program unintuitive since the user must pass the parameter as a string and the software then needs to reexpand it.

Yes, one could use an argument, but when multiple such file lists are needed, it is impossible. Supporting `nargs=-1` on options completely solves this issue.

**Comment by schuhschuh** [comment]
I second @alsimoneau. I recently discovered and switched from argparse to Typer and enjoy writing CLIs using it. However, the lack of support for multiple arguments of non-fixed length (for which fixed length `Tuple` annotation can be used) without need to prepend each value with an option key is a limitation which eventually may make me move back to argparse rather.

**Comment by fabio-porcedda** [comment]
The lack of this feature prevents me to pass from argparse to Typer for my script.

**Comment by riyadparvez** [comment]
Is there any progress on this issue? This is the only thing that's been stopping me from using typer

**Comment by gustavorps** [comment]
+1

**Comment by dromer** [comment]
Oof this is actually a big reason to stick to argparse for me. Was looking at migrating https://github.com/Wasted-Audio/hvcc to Typer but this really is inconvenient.

**Comment by alsimoneau** [comment]
I feel that the maintainers are not looking at closed issues.
It may be a good idea to open a new one referencing this to bring their attention to the issue.

**Comment by rmorshea** [comment]
The reason this isn't going to be fixed is explained [here](https://github.com/tiangolo/typer/issues/110#issuecomment-643103250). What would be more useful is if someone linked to an issue in Click which explains this limitation.

**Comment by dromer** [comment]
@Rocamonde Typer actually depends on Click internally. So yes it very much means that such functionality needs to go into Click first.

**Comment by Rocamonde** [comment]
> @Rocamonde Typer actually depends on Click internally. So yes it very much means that such functionality needs to go into Click first.

That's a totally valid reason, but I don't think users should be expected to know this limitation a priori (or even after reading the comment, that is not at all clear). Even if there is this dependency, it is not clear at first sight that an extension/workaround would not be viable. If typer implements strictly only click features, then why use the library at all? (I know there are good answers to these questions/points, but that is why I commented that this should be explained or linked to by maintainers.)

**Comment by tiangolo** [comment]
Thanks for the discussion everyone. Yes, Typer is based on Click, it does all the work underneath. It is mentioned in several places, for example here: https://typer.tiangolo.com/alternatives/#click

> Typer mainly adds a layer on top of Click, making the code simpler and easier to use, with autocompletion everywhere, etc, but providing all the powerful features of Click underneath.

If anyone wants to add support for this, it would probably be with a PR on Click directly.

**Comment by ali-ramadhan** [comment]
For anyone who stumbles upon this issue like me and is wondering about the current status of the underlying issue in click: it does not seem like click will support this (see https://github.com/pallets/click/issues/484 and https://github.com/pallets/click/issues/2771). Click can do something like `--option val1,val2,val3` with a callback to separate though, but no spaces.

A couple of alternatives that do support multiple variable length arguments are [argparse](https://docs.python.org/3/library/argparse.html) and [cyclopts](https://github.com/BrianPugh/cyclopts).

**Comment by landmanbester** [comment]
The following is possible with Click though
```python
"""
Demonstrates the ability to use: command --option val1 val2 val3
"""

import click


class OptionEatAll(click.Option):
    """
    Custom Click Option that consumes all arguments until the next option flag.
    
    This allows: --numbers 1 2 3 4 5
    Instead of: --numbers 1 --numbers 2 --numbers 3 --numbers 4 --numbers 5
    """
    
    def __init__(self, *args, **kwargs):
        self.save_other_options = kwargs.pop('save_other_options', True)
        nargs = kwargs.pop('nargs', -1)
        assert nargs == -1, f'nargs must be -1, not {nargs}'
        super().__init__(*args, **kwargs)
        self._previous_parser_process = None
        self._eat_all_parser = None

    def add_to_parser(self, parser, ctx):
        def parser_process(value, state):
            # Consume all arguments until we hit another option flag
            done = False
            value = [value]
            
            if self.save_other_options:
                # Grab everything up to the next option (starts with - or --)
                while state.rargs and not done:
                    for prefix in self._eat_all_parser.prefixes:
                        if state.rargs[0].startswith(prefix):
                            done = True
                            break
                    if not done:
                        value.append(state.rargs.pop(0))
            else:
                # Grab everything remaining
                value += state.rargs
                state.rargs[:] = []
            
            value = tuple(value)
            self._previous_parser_process(value, state)

        retval = super().add_to_parser(parser, ctx)
        for name in self.opts:
            our_parser = parser._long_opt.get(name) or parser._short_opt.get(name)
            if our_parser:
                self._eat_all_parser = our_parser
                self._previous_parser_process = our_parser.process
                our_parser.process = parser_process
                break
        
        return retval


# Type conversion callback factory
def make_type_converter(python_type):
    """
    Create a callback that converts variadic option values to a Python type.
    
    Args:
        python_type: The Python type to convert to (int, float, str, bool, etc.)
    
    Returns:
        Callback function for Click option
    """
    def converter(ctx, param, value):
        if value is None:
            return []
        
        # Click converts the tuple to its string representation
        # We need to parse it back
        if isinstance(value, str):
            # Remove outer parentheses and quotes, split by comma
            import ast
            try:
                # Use ast.literal_eval to safely parse the string representation
                parsed = ast.literal_eval(value)
                if isinstance(parsed, tuple):
                    value = parsed
                else:
                    value = (parsed,)
            except (ValueError, SyntaxError):
                # If parsing fails, treat as single value
                value = (value,)
        
        if not isinstance(value, (tuple, list)):
            value = (value,)
        
        try:
            return [python_type(v) for v in value]
        except (ValueError, TypeError) as e:
            raise click.BadParameter(f"Cannot convert to {python_type.__name__}: {e}")
    
    return converter


@click.command("typed")
@click.option(
    "--numbers",
    "-n",
    cls=OptionEatAll,
    callback=make_type_converter(float),
    required=True,
    help="Multiple integers"
)
@click.option(
    "--do-sum/--no-sum",
    default=False,
    help="Sum the numbers"
)
def typed_example(numbers, do_sum):
    """
    Example with type conversion to integers.
    
    Usage:
        python demo.py typed --numbers 1 2 3 4 5 --do-sum
        python demo.py typed -n 10 20 30 --do-sum
    """
    click.echo(f"Numbers: {numbers}")
    click.echo(f"Type: {type(numbers[0]) if numbers else None}")
    if do_sum:
        click.echo(f"Sum: {sum(numbers)}")


if __name__ == "__main__":
    typed_example()
```
Usage is as follows
```
$ python typed.py -n 1.0 2.0 3e3 --do-sum                                                                                           2 ↵
Numbers: [1.0, 2.0, 3000.0]
Type: <class 'float'>
Sum: 3003.0
```
Is there any way to do a similar thing using Typer? I really enjoy using Typer and I think this would be a very useful feature

**Comment by Jerry-Ma** [comment]
I encountered the same issue and with a bit of experiment, got the following work around (monkey patch). It would be nice we can have a proper hook to get this in without monkey patching, for example, allow a custom click Option class to be passed to `get_click_param` function:

# Multi-Argument Options for Typer

## Implementation

```python
from typing import Any
import click
import typer
import typer.core
import typer.main
from typer.models import OptionInfo


class OptionEatAll(typer.core.TyperOption):
    """Click option that consumes arguments until next option flag."""
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        kwargs["multiple"] = True
        kwargs["is_flag"] = False
        super().__init__(*args, **kwargs)
        self._previous_parser_process = None
        self._eat_all_parser = None
    
    def add_to_parser(self, parser: Any, ctx: click.Context) -> Any:
        def parser_process(value: str, state: Any) -> None:
            values = [value]
            done = False
            while state.rargs and not done:
                for prefix in self._eat_all_parser.prefixes:
                    if state.rargs[0].startswith(prefix):
                        done = True
                        break
                if not done:
                    values.append(state.rargs.pop(0))
            for val in values:
                self._previous_parser_process(val, state)
        
        retval = super().add_to_parser(parser, ctx)
        for name in self.opts:
            our_parser = parser._long_opt.get(name) or parser._short_opt.get(name)
            if our_parser:
                self._eat_all_parser = our_parser
                self._previous_parser_process = our_parser.process
                our_parser.process = parser_process
                break
        return retval


class MultiOptionInfo(OptionInfo):
    """Marker for multi-argument options."""
    is_multi_option: bool = True
    
    def __init__(self, option_info: OptionInfo) -> None:
        super().__init__(**option_info.__dict__)


def MultiOption(default: Any = ..., *param_decls: str, **kwargs: Any) -> MultiOptionInfo:
    """Create option that accepts multiple values."""
    return MultiOptionInfo(typer.Option(default, *param_decls, **kwargs))


# Monkey-patch to detect MultiOptionInfo and use OptionEatAll
_original_get_click_param = typer.main.get_click_param

def _patched_get_click_param(param: typer.models.ParamMeta):
    click_param, converter = _original_get_click_param(param)
    if isinstance(param.default, MultiOptionInfo):
        option_eat_all = object.__new__(OptionEatAll)
        option_eat_all.__dict__.update(click_param.__dict__)
        option_eat_all._previous_parser_process = None
        option_eat_all._eat_all_parser = None
        return (option_eat_all, converter)
    return (click_param, converter)

typer.main.get_click_param = _patched_get_click_param
```

## Example

```python
from typing import Annotated
from pathlib import Path
import typer

app = typer.Typer()

@app.command()
def process(
    files: Annotated[list[Path] | None, MultiOption(help="Files", exists=True)] = None,
):
    """Process multiple files."""
    if files:
        for f in files:
            print(f"Processing: {f}")

if __name__ == "__main__":
    app()
```

```bash
$ python main.py process --files file1.txt file2.txt file3.txt
Processing: file1.txt
Processing: file2.txt
Processing: file3.txt
```
