### ISSUE TITLE
[QUESTION] API Nested Documentation

### ISSUE THREAD

**Issue by ccrvlh** [tiangolo/typer#117]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Thanks a lot for the framework and congrats for the project!

In the Redoc Interactive Demo sample ([link](https://redocly.github.io/redoc/)) we can see the documentation separated by "themes".

First we can see general information (1st level), like: Introduction, CROS, Auth etc. And then we see "General" with "pet" and "store" beneath it, and then "User Management", with "user". At last we can see "Models".

Is it possible to organize the project in order to have a more organised documentation?
Thanks a lot!

**Comment by svlandeg** [comment]
[Maintenance note]: I'll go ahead and close this issue as it seems to be out-dated. In case there are follow-up questions, please open a new thread on the [discussion forum](https://github.com/tiangolo/typer/discussions) 🙏
