### ISSUE TITLE
[QUESTION] Is there a better way to pass prog_name without going through the Click command?

### ISSUE THREAD

**Issue by tarcisioe** [tiangolo/typer#118]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information (doesn't really apply).

### Description

Is it possible to inform typer of the program name without using `typer.main.get_command`?

Consider the following structure:

```
typer_test
├── __init__.py
└── __main__.py
```

And `__main__.py` having

```python
import typer

app = typer.Typer()


@app.command()
def main(i: int):
    pass


if __name__ == '__main__':
    typer.main.get_command(app)(prog_name=__package__)
```

Unless I call the command like this (in contrast to `app()`), the usage shows `__main__.py`.

Compare `app()`:

```
$ python -m typer_test                                                                                                                                                                            
Usage: __main__.py [OPTIONS] I
Try '__main__.py --help' for help.

Error: Missing argument 'I'.
```

to `typer.main.get_command(app)(prog_name=__package__)`:

```
$ python -m typer_test                                                                                                                                                                               
Usage: typer_test [OPTIONS] I
Try 'typer_test --help' for help.

Error: Missing argument 'I'.
```

I couldn't find any parameter on `Typer` to override this, neither on documentation nor by reading the source code. It seems like a pretty desirable feature to be more straightforward than having to call the Click command directly, though, so I may be missing something here. Is there any other way to do this?

**Comment by tiangolo** [comment]
It is currently not supported, and it should be supported :sweat_smile: .

---

It's actually not difficult to implement, so I'll mark it as `good first issue`.

Here are some instructions for anyone that wants to help with this :smile: 

The method at `Typer.__call__(self)` should now take `Typer.__call__(self, *args, **kwargs)`
And then it should call the generated Click command as:

```Python
return get_command(self)(*args, **kwargs)
```

To test it, I think the best/simplest way would be to have a simple application in a file, with something like `app(prog_name="custom-name")` and then call it with a sub-process (as is done in many tests) calling coverage to run it, and checking that the help text uses the `custom-name`.
