### ISSUE TITLE
Update docs with new Arguments help section

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/typer#124]
The new support for `help` parameters in *CLI arguments* from https://github.com/tiangolo/typer/pull/123 changes how the help text is generated with *CLI arguments*.

It also now shows default values by default.

So, many of the demos showing how it would look like in the terminal have to be updated to show the new real output.

* Any example that has *CLI arguments* and uses `--help` will change.
* And any example that has a default value for *CLI arguments* or *CLI options* and uses `--help`, will change too.

The task here is to read all the docs, page by page, and copy the code in the example, run the same commands as in the demonstration and update the output (copy it from the terminal) to the docs when it changes.

In most/all of the cases, it should require just to copy the example code, run it with the example commands, and copy the output back in the docs.

But it requires a lot of attention to the details to make sure not to skip/forget any example that also changes, to preserve the demonstration comments and guides, and to recognize when there are changes.

And the changes are probably a lot, spread through all the docs :sweat_smile:

**Comment by victorphoenix3** [comment]
I could work on this! :)
