### ISSUE TITLE
Use Optional in docs

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/typer#125]
As part of https://github.com/tiangolo/typer/issues/124, I updated the initial docs that introduce `Optional` for values that default to `None`.

We should have all the docs that have *CLI arguments* or *CLI options* with a default value of `None` to be declared using `Optional[some_type]`, that way the editor will be able to help to detect unsafe operations that assume that the value is not `None`.

The quick intro to `Optional` is now here: https://typer.tiangolo.com/tutorial/#python-types

**Comment by rkbeatss** [comment]
will be working on it 🥰

**Comment by tiangolo** [comment]
Thanks @rkbeatss ! :rocket: :cake:
