### ISSUE TITLE
[QUESTION] How to test command line argument parsing only

### ISSUE THREAD

**Issue by aschreyer** [tiangolo/typer#126]
Is it possible to run tests with the existing framework (CliRunner) to only test the parsing but not running the actual application?

For example, to simply check that syntax bugs such as providing a wrong option for a boolean type that uses `is_flag=False` (or the inverse scenario) can be easily detected, and possibly parametrized using py.test without running the actual application logic.

**Comment by tiangolo** [comment]
The `CliRunner` calls the `CliRunner` from Click directly: https://click.palletsprojects.com/en/7.x/testing/

I can't think of a way to make it do what you want. Although I'm having trouble imagining a use case for that.

Maybe could you write a simple example showing what you want to achieve?
