### ISSUE TITLE
[BUG] Multiple value option gives tuple and not list

### ISSUE THREAD

**Issue by jayqi** [tiangolo/typer#127]
### Describe the bug

The standard way to configure an option that expects multiple values is to declare with `List`, as [described in the docs](https://typer.tiangolo.com/tutorial/multiple-values/multiple-options/).

However, this provides a tuple of values, and not a list of values, as one would expect based on the type hint declaration. It also contradicts the [documentation](https://typer.tiangolo.com/tutorial/multiple-values/multiple-options/), which states "You will receive the values as you declared them, as a list of str".

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

* Create a file `main.py` with:

```Python
from typing import List
import typer


def my_command(opt: List[str] = ["foo", "bar"]):
    typer.echo(opt)
    typer.echo(type(opt))


if __name__ == "__main__":
    typer.run(my_command)
```

* Call it with:

```bash
python main.py
```

  * It outputs:

```
('foo', 'bar')
<class 'tuple'>
```

* Call it with:

```bash
python main.py --opt baz
```

  * It outputs:

```
('baz',)
<class 'tuple'>
```

### Expected behavior

I would expect to get a container of values that is class `list` as declared. 

### Environment

* OS: macOS 10.15.4
* Python 3.6.10
* Typer 0.3.0

**Comment by ovezovs** [comment]
I was able to reproduce this issue. Would this be considered a bug or a documentation issue, @tiangolo? I'd like to work on this.

**Comment by ovezovs** [comment]
UPDATE: I have discussed this with my MLH mentor and we concluded that it was a bug, however, I am not sure if the bug is in the typing library or Typer itself.

**Comment by tiangolo** [comment]
Hey @ovezovs ! Thanks!

Yes, I think it would probably make sense to ensure that the value passed is a `list` in this case, converting it to a list if it is not.

**Comment by hellowhistler** [comment]
> UPDATE: I have discussed this with my MLH mentor and we concluded that it was a bug, however, I am not sure if the bug is in the typing library or Typer itself.

Hi @ovezovs, are you still planning on looking into this (or already working on it)? I encountered this bug in the wild, and if you've changed your mind, I'd be interested in trying to fix it.

**Comment by ovezovs** [comment]
> Hi @ovezovs, are you still planning on looking into this (or already working on it)? I encountered this bug in the wild, and if you've changed your mind, I'd be interested in trying to fix it.

Feel free to take on it.

**Comment by Andrew-Sheridan** [comment]
As an extra layer to this, if an option is declared as `foo: Optional[List[str]] = typer.Option(None)` it should provide `None` if nothing is passed. Currently it is providing `()`, an empty tuple.

In comparison `bar: Optional[str] = typer.Option(None)` _does_ provide `None` when missing, as expected.

Would this be considered the same issue, or should I raise a new one?

**Comment by tiangolo** [comment]
Thanks for the clear example @jayqi! :nerd_face: :cake: 

And thanks for the discussion everyone. :coffee: 

@Andrew-Sheridan, could you please create a new issue with that example?

This was fixed by @hellowhistler in https://github.com/tiangolo/typer/pull/143

It will be available in the next release, in some hours, Typer version `0.4.2` :tada:

**Comment by Andrew-Sheridan** [comment]
> @Andrew-Sheridan, could you please create a new issue with that example?

Created #410 with the example
