### ISSUE TITLE
[BUG] - Arguments with leading hyphens in the name: escaping?

### ISSUE THREAD

**Issue by andremoeller** [tiangolo/typer#134]
### Describe the bug

I expect that my users will give my app optional arguments do contain leading double hyphens like `--input`. But I cannot parse optional arguments that have a single ("-") or double ("--") before the rest of the word, since such an argument does not exist.

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

* Create a file `main.py` with:

```from typing import Optional, List
import typer


app = typer.Typer()


@app.command()
def goodbye(app_args: Optional[List[str]] = typer.Argument(None)):
    print(app_args)


if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python main.py arg1, --arg2, val2
```

* It outputs:

```
no such option: --arg2
```

* But I expected it to output:

```
('arg1,', '--arg2,', 'val2')
```

### Expected behavior

I wanted to retain arguments with single- or double-hypens. I could find no way to escape them and interpret them literally. I expect optional arguments that do contain leading double hyphems like `--input`.

### Environment

* OS: [e.g. Linux / Windows / macOS] Mac OS
* Typer Version [e.g. 0.3.0], get it with: 0.3.0

```bash
python -c "import typer; print(typer.__version__)"
```

* Python version, get it with:

```bash
python --version 3.7.3
```

**Comment by rkbeatss** [comment]
will look into this!

**Comment by tiangolo** [comment]
Hey, as Typer is based on Click, you can do the same as with Click: https://click.palletsprojects.com/en/7.x/arguments/#option-like-arguments

You would use it like:

```console
$ python main.py -- arg1 --arg2 val2

('arg1', '--arg2', 'val2')
```
