### ISSUE TITLE
[BUG] typer.Argument does not take `help` as an argument

### ISSUE THREAD

**Issue by creativesands** [tiangolo/typer#139]
Although the online docs for `typer.Argument` shows that it takes `help` and `show_default` as parameters, it doesn't take such parameters and there doesn't seem to be another way to provide help for arguments other than typing it out as docstring manually. `typer.Option` seems to be taking these parameters.

### Way to reproduce
I'm on a mac with typer==0.2.1

```python
import typer

def main(name: str = typer.Argument("World", help="Who to greet", show_default=True)):
    typer.echo(f"Hello {name}")

if __name__ == "__main__":
    typer.run(main)
```

**Comment by creativesands** [comment]
The current version of typer is 0.3.0; but installing `typer-cli` after installing `typer` lowers the version to 0.2.1 which does not have TyperArguments such as `help`, `show_default` etc. Perhaps typer-cli requirements version needs to be updated.

**Comment by tiangolo** [comment]
Thanks for the report, this is actually related to Typer CLI, not to Typer itself, there's an issue tracking it here: https://github.com/tiangolo/typer-cli/issues/19
