### ISSUE TITLE
[QUESTION] Is it possible to remove the default options (--install-completion, ..) in a typer based CLI?

### ISSUE THREAD

**Issue by jokurz** [tiangolo/typer#141]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [ ] I already searched in Google "How to X in Click" and didn't find any information.

### Description
Is it possible to remove the default options (--install-completion, ..) in a typer based CLI?

By default we always have the options `--install-completion` and `--show-completion` when using typer:
```
python main.py --help
Usage: main.py [OPTIONS] NAME LASTNAME

Arguments:
  NAME      [required]
  LASTNAME  [required]

Options:
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or customize the installation.
  --help                Show this message and exit.
```
Is it possible to hide that? In case an End User is not familiar with Typer or we are using a non-supported shell (ksh) those options could be confusing/distracting.

### Additional context
Question has been asked on [stackoverflow](https://stackoverflow.com/questions/62494622/is-possible-to-remove-the-default-options-in-a-typer-based-cli?newreg=bdbd86a055534c818b88d03dedd2612f) as well.

**Comment by hellowhistler** [comment]
This works but requires using the [Click app](https://typer.tiangolo.com/tutorial/using-click/). Not sure if there's a better solution.

```python
import typer

app = typer.Typer()


@app.command()
def main(name: str):
    typer.echo(f"Hello {name}!")


cli = typer.main.get_command(app)
cli.params = [
    param
    for param in cli.params
    if param.name != "show_completion" and param.name != "install_completion"
]


if __name__ == "__main__":
    cli()
```

**Comment by jokurz** [comment]
@hellowhistler: Thanks for your answer! Might not be the cleanest solution but at least it works!

**Comment by ycd** [comment]
I found a better solution, I met the same problem today,i couldn't find anything except this issue and the Stackoverflow question mentioned above,  so dived in the source to find how Typer automatically adds this two options in app, so i found this, when **Typer** initialiazing itself it automatically sets `add_completion` to True
 
    class Typer:
        def __init__(add_completion: bool = True)

So when you initialiazing your app you can add this

    app = typer.Typer(add_completion=False)

This is how it looks after you add `add_completion=False`


    Usage: main.py [OPTIONS] COMMAND [ARGS]...

    Options:
      --help  Show this message and exit.

**Comment by tiangolo** [comment]
Thanks for the help here @ycd ! :clap: :bow: 

Thanks for reporting back and closing the issue :+1:

**Comment by StephenCarboni** [comment]
Shouldn't this be in the docs?

**Comment by coreegor** [comment]
Note that when you set ` add_completion=False` Typer does not invoke `typer.completion.completion_init()`. This causes the original Click completions to run by default.
