### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by nareshbs** [tiangolo/typer#160]
### Description

How can I [...]?
does typer support a session oriented CLI  . specifically, assume I want to implement something like Cisco CLI,  or something like cmd2. in python.  I need to have a session with the back-end and the front end should give me the ability to to a loop run

Is it possible to [...]?

### Additional context
Session Oriented CLIs are needed for managing the Remote devices etc.

**Comment by tiangolo** [comment]
I'm not sure what you mean with a session oriented CLI.

If you refer to doing authentication with a backend and then keeping it for future commands, then sure, you can implement it, but it wouldn't really depend on Typer.

You would probably ask for a username and password, or launch a browser with a device OAuth2 login website or similar. And then you could store the authentication token in the application directory: https://typer.tiangolo.com/tutorial/app-dir/ and re-use it for the next commands.
