### ISSUE TITLE
Docstring help for commands gets truncated

### ISSUE THREAD

**Issue by eddsalkield** [tiangolo/typer#165]
### Describe the bug

Long help messages for commands get truncated instead of being split onto multiple lines.

### To Reproduce

* Create a file `main.py` with:

```Python
import typer

app = typer.Typer()


@app.command()
def create(username: str):
    """
    Some internal utility function to create.
    """
    typer.echo(f"Creating user: {username}")


@app.command()
def delete(username: str):
    """
    Some internal utility function to delete things this help is very
    long yes.
    """
    typer.echo(f"Deleting user: {username}")


if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python main.py --help
```

* It outputs:

```
Usage: main.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or
                        customize the installation.

  --help                Show this message and exit.

Commands:
  create  Some internal utility function to create.
  delete  Some internal utility function to delete things this line is very...
```

* But I expected it to output:

```
Usage: main.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or
                        customize the installation.

  --help                Show this message and exit.

Commands:
  create  Some internal utility function to create.
  delete  Some internal utility function to delete things this line is very
          long yes.
```

### Expected behavior

Insert line breaks intelligently at word endings where possible, instead of truncating.

### Environment

* OS: Linux
* Typer version: 0.3.2
* Python version: 3.8.5

**Comment by scott2b** [comment]
If I understand correctly, this is inherited behavior from Click. If you request help for a specific command, the full text will be shown. I think this is more of a design choice than a bug .. the text is intentionally being truncated when shown for all of the commands as a matter of economy of space in order to accommodate multiple commands.

However, I think this design choice gets thrown for a bit of a curve in Typer usage patterns specifically in that if there is only a single command, typer "knows" to execute that command as a default, and yet the doc output from --help does not really reflect this usage pattern, still showing the single default command as a command in the Commands list, and with truncated help.

**Comment by daddycocoaman** [comment]
This is a Click issue https://github.com/pallets/click/issues/486. The help formatter uses the first line of the docstring when printing it out (or can be overridden with `short_help`) and cuts off at 80 characters.  But it might make things look messy for really long doc strings to be seen in the `commands` section of a parent command. If you want to see the full help, you could just run `--help` on the command itself.

The recommended solution in the past (which won't give you exactly the output you asked for) was something like this. It's still not multiline though.

```python
import typer

app = typer.Typer(context_settings=dict(max_content_width=9999))


@app.command()
def create(username: str):
    """
    Some internal utility function to create.
    """
    typer.echo(f"Creating user: {username}")


@app.command()
def delete(username: str):
    """
    Some internal utility function to delete things this help is very
    long yes.
    """
    typer.echo(f"Deleting user: {username}")

if __name__ == "__main__":
    app()
```

```
Usage: longhelp.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or customize the installation.
  --help                Show this message and exit.

Commands:
  create  Some internal utility function to create.
  delete  Some internal utility function to delete things this help is very long yes.
```

**Comment by tiangolo** [comment]
Yep, what @daddycocoaman says :nerd_face: :point_up:

**Comment by eddsalkield** [comment]
Although the issue lies in click rather than typer, I feel this should remain open because it's not resolved.
