### ISSUE TITLE
[QUESTION] Global option anywhere in the command line?

### ISSUE THREAD

**Issue by trondth** [tiangolo/typer#166]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Is it possible to implement a global option so it can be added anywhere in the commandline and to be displayed in the help for each subcommand.

### Additional context

It is well documented how to create a global option with callback, but it seems to have some limitations. It seems to me that a global option «foo» can only be set like this:

`command --foo bar subcommand`

but not like this:

`command subcommand --foo bar`

And also, the help for «foo» will only be displayed on:

`command --help`

not

`command subcommand --help`

Is there a way to make the global option more flexible?

**Comment by rino0601** [comment]
IMO,
Duplicate of #153

**Comment by trondth** [comment]
> IMO,
> Duplicate of #153

Yes. Reading the last reply in #153, I agree. (I first mistook it for sharing options between a subset of commands)

**Comment by tiangolo** [comment]
In that case, we can continue in that issue, right?

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by trondth** [comment]
Yes, I should have closed this back in 2020. Thanks for the feedback.

> In that case, we can continue in that issue, right?
> 
> > Sorry for the long delay! see_no_evil  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
