### ISSUE TITLE
How different is typer from click command?

### ISSUE THREAD

**Issue by mabounassif** [tiangolo/typer#169]
Just wondering how different Typer is from Click Command.

Naively, I would think it would be better to consolidate the effort? Now the end user (me) is conflicted.

**Comment by astrojuanlu** [comment]
Arrived here from Google, I think this answers the question https://typer.tiangolo.com/alternatives/#click

**Comment by dreamlayers** [comment]
The most important differences for me are that Click has many fewer dependencies, and Click is faster. Running a small utility on a Raspberry Pi 2 B using Raspbian Bookworm, Click takes 1 second and Typer takes 2 seconds. I could say Typer syntax is more elegant, but with such differences, I am using Click.
