### ISSUE TITLE
[BUG] Optional multi-value option returns empty tuple instead of None

### ISSUE THREAD

**Issue by jaklan** [tiangolo/typer#170]
### Describe the bug

Optional multi-value option returns empty tuple instead of `None`.

### To Reproduce

* Create a file `main.py` with:

```Python
from typing import List, Optional

import typer

app = typer.Typer()


@app.command()
def main(jobs: Optional[List[str]] = None): # or `typer.Option(None)`
    print(jobs)


if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python main.py
```

* It outputs:

```
()
```

* But I expected it to output:

```
None
```

### Expected behavior

The expected behavior for an empty parameter annotated with `Optional` and `= None` is both [documented](https://docs.python.org/3/library/typing.html#typing.Optional) and commonly known - it should be just `None`. And that's also how it works in Typer, but for some reason - only for single-value options.

### Environment

* OS: macOS
* Typer version: 0.3.2
* Python version: 3.8.5

**Comment by jaywonchung** [comment]
I encountered the same problem as well. Did you find a workaround?

**Comment by svlandeg** [comment]
Confirmed that this still seems like an issue, though the output on the current version of Typer v0.9.0 is `[]`, not `()` (which is still not the expected `None`)

**Comment by svlandeg** [comment]
PR to fix this issue: https://github.com/tiangolo/typer/pull/664
