### ISSUE TITLE
[DOC] Confirmation prompt part is located at two different places

### ISSUE THREAD

**Issue by nalepae** [tiangolo/typer#172]
Confirmation prompt part is located at two different places in the documentation.

**First place:** https://typer.tiangolo.com/tutorial/options/prompt/
![image](https://user-images.githubusercontent.com/4943830/94872080-f38b8f00-044b-11eb-869b-481e2030f8f9.png)

**Second place:** https://typer.tiangolo.com/tutorial/options/password/
![image](https://user-images.githubusercontent.com/4943830/94872117-0a31e600-044c-11eb-9edf-18137a0ecc21.png)

**Comment by nalepae** [comment]
Also, I guess the little stars here :
https://typer.tiangolo.com/tutorial/parameter-types/datetime/
![image](https://user-images.githubusercontent.com/4943830/94909342-51979100-04a3-11eb-8d3e-58435e2548d0.png)

are not what you intended to have :)

**Comment by tiangolo** [comment]
Thanks! About the parameter explained in both places, it's relevant in both cases, so I would rather leave it as is. About the datetime format, it was fixed here: https://github.com/tiangolo/typer/pull/220 thanks!

**Comment by PHclaw** [comment]
For the autocompletion not working in zsh:

The most common cause is the completion file not being in $fpath. Check:

```bash
# In your .zshrc:
fpath=(~/.zfunc $fpath)
autoload -Uz _compinit
compinit

# Then source the completion file:
source <(your-app --show-completion zsh)
```

Or install using typer's built-in install:
```python
# In your CLI app:
app = typer.Typer()
@app.command()
def main(install_completion: bool = False):
    if install_completion:
        typer.launch("zsh")  # Opens instructions
```
