### ISSUE TITLE
[FEATURE] Decouple from Click to make the codebase more readable

### ISSUE THREAD

**Issue by jackric** [tiangolo/typer#175]
### Is your feature request related to a problem

I forked Typer to work on a pull request (for #77). I was anticipating the work would take me something like 45 minutes. Actually - the global solution (registering a type handler globally) was easy enough. The cleaner solution of allowing type handlers to be registered on individual `Typer` instances proves much harder.
I'm finding the codebase has some blatant code smells that stem from its embrace of Click. E.g. taking so many parameters below to fit the various Click param classes:
![image](https://user-images.githubusercontent.com/259713/95513656-972bf080-09b2-11eb-9dd5-98ffa61ab6b9.png)

### The solution you would like

Initiative to make a command and argument library, which leverages type annotations, exist on its own without being a proxy to Click.

### Describe alternatives you've considered

Could start my own library for this but would rather influence a larger ecosystem player.

**Comment by mikenerone** [comment]
Whether a revamp of `typer` or a new project altogether, a Pydantic-oriented approach might be worth considering as part of this (see some related discussion at #111). [`pydantic-cli`](https://github.com/mpkocher/pydantic-cli) has some relevant ideas (but is unusable in many cases IMO due to its lack of support for positional arguments and is, sadly, built on `argparse`).

**Comment by tiangolo** [comment]
The idea with Typer was to take advantage of all the power from Click, it is what does all the work underneath. Here you would be asking me to re-implement all of Click. :sweat_smile:

That's something I wouldn't be able to take on right now.

There are several quirks in how Click works that make me consider ideas like this, but probably I won't be able to tackle that soon.

I would also need to check how many people depend on the integrations with Click and the ability to mix Typer and Click apps on the same codebase. But anyway, that will be later, if it happens.
