### ISSUE TITLE
[QUESTION] Recommended way for optional paths like unix tools

### ISSUE THREAD

**Issue by laserson** [tiangolo/typer#177]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

What is the standard/recommended way to implement a CLI tool with Typer that has similar semantics to standard pipe-able unix tools? By default the tool would read/write to stdin/stdout, but if paths are provided they are used instead. Would you take an argument of type `Path` that is optional? Would be nice to have a way to eliminate some boilerplate.

**Comment by laserson** [comment]
I gave up too quickly. Answer is `click.open_file()`.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
