### ISSUE TITLE
Commands in separate files loses arguments and options help description

### ISSUE THREAD

**Issue by v1sion** [tiangolo/typer#178]
Before everything thank you for the great work with typer :) 

### Describe the bug

When the commands are in one single file we have the commands arguments and options help description, but if we separate them in different files we lose this help description.

#### Single File
```Python
// main.py

import typer

app = typer.Typer()


@app.command()
def create(username: str):
    typer.echo(f"Creating user: {username}")


@app.command()
def delete(
    username: str,
    force: bool = typer.Option(..., prompt="Are you sure you want to delete the user?"),
):
    if force:
        typer.echo(f"Deleting user: {username}")
    else:
        typer.echo("Operation cancelled")


if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python main.py delete --help
```

* It outputs:

```
Usage: main.py delete [OPTIONS] USERNAME

Arguments:
  USERNAME  [required]

Options:
  --force / --no-force  [required]
  --help                Show this message and exit.
```

#### Separated Files

```Python
// main.py

import typer
import delete
import create

app = typer.Typer()
app.add_typer(create.app, name="create")
app.add_typer(delete.app, name="delete")

if __name__ == "__main__":
    app()
```

```Python
// delete.py
import typer

app = typer.Typer()


@app.command()
def delete(
    username: str,
    force: bool = typer.Option(..., prompt="Are you sure you want to delete the user?"),
):
    if force:
        typer.echo(f"Deleting user: {username}")
    else:
        typer.echo("Operation cancelled")
```

* Call it with:

```bash
python main.py delete --help
```

* It outputs:

```
Usage: main.py delete [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  delete
```

* But I expected it to output:

```
Usage: main.py delete [OPTIONS] USERNAME

Arguments:
  USERNAME  [required]

Options:
  --force / --no-force  [required]
  --help                Show this message and exit.
```

### Expected behavior

Even if the commands are separated in different files would be nice to still have the help description :)

### Environment

* OS: macOS
* Typer Version: 0.3.2
* Python version: 3.8.6

**Comment by tomgrin10** [comment]
This is not a bug, when you are calling `app.add_typer(create.app, name="create")`, you are creating a subcommand group named `create` and adding all commands in `create.app` into it.
So in the end your commands look like this:
```
create
|-- create
build
|-- build
```

**Comment by alextremblay** [comment]
Agreed, this is not a bug.

in your example, if you run `./main.py delete delete --help`, you will get the help text you were expecting to see from `./main.py delete --help`
generally speaking, it's better not to break out individual typer commands into separate modules, it's better to break out command groups into separate modules, but if you genuinely need to be able to import individual commands from separate modules, typer allows that too.

Ex:
```python
// main.py

import typer
import delete
import create

app = typer.Typer()
app.command()(create.create)
app.command()(delete.delete)

if __name__ == "__main__":
    app()
```
```python
// delete.py
import typer

def delete(
    username: str,
    force: bool = typer.Option(..., prompt="Are you sure you want to delete the user?"),
):
    if force:
        typer.echo(f"Deleting user: {username}")
    else:
        typer.echo("Operation cancelled")
```

You'll notice that `app.command()(delete.delete)` in main.py replaces the `@app.command()` decorator on the `delete` function in the `delete` module

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
