### ISSUE TITLE
[FEATURE] Typer building a package guide with vanilla setup.py not poetry

### ISSUE THREAD

**Issue by mcsheehan** [tiangolo/typer#183]
Typer heavily uses poetry in it's setup guides. Poetry is tricky to setup for private repositories, such as aws codeartifact at the moment. For this reason we are delaying our migration to poetry till this is more readily supported. I'd like to use typer, but the guides depend heavily on poetry (and i therefore assume typer does as well?).

It would be really nice to use typer independently of poetry. As we want to buy into a skinny cli library with a clean interface (typer looks nice) not an entire ecosystem, with poetry as a mandatory build tool.

If creation of a building a package guide is possible without using poetry and having entrypoints that would be amazing.

**Comment by Andrew-Sheridan** [comment]
@mcsheehan you can use `setup.py`. Just add 
``` 
entry_points={"console_scripts": [f"foo-cli = foo_package.cli:app"]},
```
to the `setup()` call.

**Comment by mcsheehan** [comment]
Poetry has added support for authentication to private repositories (including aws code artifact). As such, this ticket is now redundant.
