### ISSUE TITLE
Force new line in docstring.

### ISSUE THREAD

**Issue by joaonc** [tiangolo/typer#188]
How do I force a a new line either in the docstring or in the `help` argument?

It's either a blank line (ie, 2 new lines) or nothing, it looks like.

ex:
Happening:
```
"""
This is line 1. Would like to force line break here.
This is line 2, except it's not, continues in front of the previous line.
"""
```
What I would like to do:
```
"""
This is line 1. Would like to force line break here.
This is line 2, for real, with no blank line between this and the previous line.
"""
```

**Comment by umeshmohan** [comment]
You can prevent rewrapping by adding a line with just "\b" before the paragraph that you do not want rewrapped.
Source: https://click.palletsprojects.com/en/7.x/documentation/#preventing-rewrapping

**Comment by joaonc** [comment]
That worked, tx!

**Comment by tiangolo** [comment]
Thanks for the help here @umeshmohan ! 👏  🙇 

Thanks for reporting back and closing the issue @joaonc  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
