### ISSUE TITLE
[DOC] Dependency with poetry

### ISSUE THREAD

**Issue by tupuinui** [tiangolo/typer#190]
With poetry 1.1.4, you need to do: `poetry add "typer[all]"` instead of `poetry add typer[all]` as suggested in the [doc](https://typer.tiangolo.com/tutorial/package/#dependencies-and-environment). Otherwise you have an error: 
`zsh: no matches found: typer[all]`.
This might be due to my bash being zsh, I don't know.

**Comment by sanders41** [comment]
I get this error also (also using zsh). `poetry add typer -E all` also works.

**Comment by Senpos** [comment]
Right, that's the `zsh` thing.
It is not related to `typer` or `poetry` directly.

Please, check [this SO answer](https://stackoverflow.com/a/30539963) by Lukas Graf for an explanation and a workaround.

**Comment by tupuinui** [comment]
> Right, that's the `zsh` thing.
> It is not related to `typer` or `poetry` directly.
> 
> Please, check [this SO answer](https://stackoverflow.com/a/30539963) by Lukas Graf for an explanation and a workaround.

Sure sure, but as more and more people are using zsh, it might be worth pointing this out or having a better error message.

**Comment by Senpos** [comment]
`it might be worth pointing this out or having a better error message.`
Do you mean, it should be in the `poetry` documentation? I guess, `pip` should have this mentioned somewhere too.
Though this errors comes from the `zsh` directly, it does not even hit `poetry` / `pip` / `typer`.

**Comment by tupuinui** [comment]
> > it might be worth pointing this out or having a better error message.
> 
> Do you mean, it should be in the `poetry` documentation? I guess, `pip` should have this mentioned somewhere too.
> Though this errors comes from the `zsh` directly, it does not even hit `poetry` / `pip` / `typer`.

Ah indeed you're right, I understand now what you meant by a zsh thing! Well then I would say that something in the doc would be a nice to have. I mean if with bash the "zsh way" would work, I would just change it to this then.

But feel free to close this as it is a bit out of scope I guess 😄

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
