### ISSUE TITLE
[QUESTION] Is there a way to use Typer to build a CLI program with plugins support?

### ISSUE THREAD

**Issue by lecovi** [tiangolo/typer#192]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

I'm new to typer and I was wondering 🤔 if there any change to have a typer program working as a command for another typer program.

Let's say you have a CLI called `pier`, built with Typer of course 😉:

```bash
$ pier
Usage: pier [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.

  --help                          Show this message and exit.

Commands:
  info
  version
```

Let's suppose that another user wants to extend `pier` functionality adding a `check` sub-command.  Something that the final user will install with `pip`:

```bash
$ pip install pier pier-check
```
The final result will be:

```bash
$ pier
Usage: pier [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.

  --help                          Show this message and exit.

Commands:
  info
  version
  check
```

**Comment by eis-si-github** [comment]
typer allows you to add other typer apps (possibly from different modules) as subcommands, so what you're asking for is definitely possible.

one thing you could try is follow this guide to collect plugin modules and import them all into a dictionary
https://packaging.python.org/guides/creating-and-discovering-plugins/

and then once you have the `discovered_plugins` populated, you could do something like this:
```python
for plugin in discovered_plugins.values():
    app.add_typer(plugin.app)
```

For this to work, each plugin module would have to define a typer app with a global name `app` and define an app callback with a command name.
Ex:
```python
#file some_plugin_module.py
import typer

app = typer.Typer()

@app.callback('check')
def check_cmd_group():
    """
    Commands for checking various things in pier
    """
```

I haven't tested this out, but i believe it will work. Good luck, and let me know how it goes, I may end up implementing something like this myself in the future

**Comment by Andrew-Sheridan** [comment]
@lecovi A discussion which explores this can be found in another issue. In short @eis-si-github has the right idea. 
- https://github.com/tiangolo/typer/issues/119

**Comment by tiangolo** [comment]
Thanks for the discussion everyone!

I haven't tried this myself but I think @eis-si-github has the right idea. :bulb:
