### ISSUE TITLE
[BUG] help messsage does not work when installed as console script

### ISSUE THREAD

**Issue by noklam** [tiangolo/typer#198]
### Describe the bug
1. `python main.py --help` - work as expected
2. test_typer - does not work

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

* Create a file `main.py` with:
![image](https://user-images.githubusercontent.com/18221871/100206178-f634cd00-2f40-11eb-84df-42825ae0c9b5.png)

Run it with python or as a standalone console script

```Python
import typer


def main(name: str):
    typer.echo(f"Hello {name}")


if __name__ == "__main__":
    typer.run(main)
```

* It outputs:
Error with missing argument

* But I expected it to output:
The help message

### Expected behavior

The help message

### Environment

* OS: Window
* Typer Version : 0.3.2

```bash
python -c "import typer; print(typer.__version__)"
```

* Python version, get it with:
3.7.5

**Comment by noklam** [comment]
It seems also break the cli, not just help message.

![image](https://user-images.githubusercontent.com/18221871/100207682-d7373a80-2f42-11eb-8693-c389a93da29f.png)

**Comment by noklam** [comment]
Not sure if this is the standard solution, I wrap main inside another function and everything works now
```
import typer


def runner(name: str = typer.Option(None)):
    typer.echo(f"Hello {name}")


def main():
    typer.run(runner)

if __name__ == "__main__":
    main()
```

**Comment by tiangolo** [comment]
You shouldn't point your entrypoint to the plain function, that makes `setuptools` use your Python code directly, without using Typer.

In that case, you should create a Typer application object, and then point your entrypoint to that object. Check an example creating a package here: https://typer.tiangolo.com/tutorial/package/#add-a-script

It uses Poetry, so it has the `script` as the equivalent of your setuptools `entrypoint`.
