### ISSUE TITLE
[FEATURE] Handling Path / File arguments easily

### ISSUE THREAD

**Issue by Senpos** [tiangolo/typer#2]
`click` has an opportunity to handle [Path ](https://click.palletsprojects.com/en/7.x/api/#click.Path) and [File ](https://click.palletsprojects.com/en/7.x/api/#click.File) arguments with ease.
Is there an option to do the same in `typer`?

I am not gonna lie, that was so fun to just put this into the `click.argument` parameters and let the library do all the magic and checking for me:
```python
@click.command()
@click.argument(
    "filename",
    type=click.Path(exists=True, dir_okay=False, resolve_path=True, readable=True),
)
def path_command(filename):
    ...
```
The only inconvenience I had - it did not return a `pathlib.Path` object, so I had do manually create it, but that is not a big deal.

As I can see, `click.Path` type is not exposed in the `typer` module. And using `pathlib.Path` as a type for my parameter is not helping in any way.

Thanks for your time! I would like to know what you think about it.

**Comment by Senpos** [comment]
Just wanted to point out, that importing `click` excplicitly and passing `click.Path(...)` as a type for my argument did not work, as it rise `RuntimeError: Type not yet supported: <click.types.Path object at 0x00000000022EB848>`

**Comment by Senpos** [comment]
Hmm, that is interesting.
There is [a built-in model](https://github.com/tiangolo/typer/blob/7fc3d1224a02015a6bbf75939b5b6a40941960ce/typer/models.py#L145), which allows to use most (if not all) click-specific attributes.
I am not sure how to use it though.

**Comment by bandaangosta** [comment]
> Hmm, that is interesting.
> There is [a built-in model](https://github.com/tiangolo/typer/blob/7fc3d1224a02015a6bbf75939b5b6a40941960ce/typer/models.py#L145), which allows to use most (if not all) click-specific attributes.
> I am not sure how to use it though.
> 
> **upd.**
> 
> Ah, I see, it works similarly to route parameters it FastAPI!
> 
> ```python
> @app.command()
> def path_command(path: Path = typer.Argument(".", exists=True, dir_okay=False)):
>     ...
> ```
> 
> That's cool!

Same principle applies, for example, to include additional attributes to options (still pending in documentation). In this case, an option help string:
```
@app.command()
def hello(name: str = typer.Option(help='First name of a person', default='Unknown')):
    typer.echo(f"Hello {name}")
```
```
$ python main.py hello --help
Usage: main.py hello [OPTIONS]

Options:
  --name TEXT  First name of a person
  --help       Show this message and exit.

```

**Comment by tiangolo** [comment]
Thanks @Senpos for updating the issue! Yep, you found it. Also thanks @bandaangosta !

Yep, there's a bunch of docs to add :sweat_smile: 

For paths and files at least there are docs now :tada: :memo: https://typer.tiangolo.com/tutorial/parameter-types/path/
