### ISSUE TITLE
[QUESTION] How to add short option "-h" to "--help" callback

### ISSUE THREAD

**Issue by JeromeK13** [tiangolo/typer#201]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I add a short option "-h" to the existing "--help" callback?

**Comment by daddycocoaman** [comment]
Since Typer is based on Click, you can do something like this to your Typer constructor:

```python
app = typer.Typer(context_settings={"help_option_names": ["-h", "--help"]})
```

**Comment by richieadler** [comment]
I have the following code and the context_settings doesn't have the intended effect:

```python
import typer

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

app = typer.Typer(context_settings=CONTEXT_SETTINGS)

@app.command()
def main(nom: str):
    print(f"Hello {nom}")

if __name__ == '__main__':
    app()
```

**Comment by joberbr** [comment]
@richieadler the context_settings should be place inside the command decorator like so:

`import typer

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

app = typer.Typer()

@app.command(context_settings=CONTEXT_SETTINGS)
def main(nom: str):
    print(f"Hello {nom}")

if __name__ == '__main__':
    app()`

I was able to make work in my code

**Comment by richieadler** [comment]
@joberbr The problem with that approach is that I need to set those parameters for each command, but my intent is to make it global for all commands. The completion options, for me, are noise, and I want to remove them completely from all commands.

Is it really impossible to do?

**Comment by joberbr** [comment]
@richieadler I am really new to this too but this option also worked with multiple commands

```
import typer

app = typer.Typer()


@app.command()
def create(username: str):
    typer.echo(f"Creating user: {username}")


@app.command()
def delete(username: str):
    typer.echo(f"Deleting user: {username}")


@app.callback(context_settings={"help_option_names": ["-h", "--help"]})
def main(ctx: typer.Context):
    """
    Manage users in the awesome CLI app.
    """
    typer.echo(f"About to execute command: {ctx.invoked_subcommand}")


if __name__ == "__main__":
    app()
```

**Comment by daddycocoaman** [comment]
> @joberbr The problem with that approach is that I need to set those parameters for each command, but my intent is to make it global for all commands. The completion options, for me, are noise, and I want to remove them completely from all commands.
> 
> Is it really impossible to do?

Ohhhh...you want to remove the completion options? That's a separate parameter. You can add `--help/-h` to all your commands via context_settings. But if you also want to remove the `--install-completion/--show-completion`, then you need to set it like this:

```python
import typer


app = typer.Typer(
    context_settings={"help_option_names": ["-h", "--help"]}, add_completion=False
)


@app.command()
def main(nom: str):
    print(f"Hello {nom}")


@app.command()
def main2(nom: str):
    print(f"Bye {nom}")


if __name__ == "__main__":
    app()
```

**Comment by richieadler** [comment]
@daddycocoaman as you noted above, it works for more than one command, but not for a single one. Weird.

**Comment by alexreg** [comment]
Should this not be reopened? It seems to be a bug that it (still) doesn't work for a single command.

**Comment by Midnighter** [comment]
Even better, I think this should be the default 😉
