### ISSUE TITLE
[QUESTION] testing typer.confirm 

### ISSUE THREAD

**Issue by koaning** [tiangolo/typer#205]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

I've gotten two commands. 

```python
# typermain.py
from typing import List

import typer
from rich.console import Console

app = typer.Typer(name="yo", add_completion=False, help="My Awesome CLI[tm]")
console = Console()

@app.command()
def create_db(table: str = typer.Option(..., prompt="What is the name of the table?", confirmation_prompt=True)):
    console.print(f"Creating table in database {table}", style="green")

@app.command()
def delete_db(table: str = typer.Option(..., prompt="What is the name of the table?", confirmation_prompt=True)):
    sure = typer.confirm("Are you really sure?")
    if sure:
        console.print(f"Deleting table in database {table}", style="red")
    else:
        console.print(f"Back to safety!", style="green")
```

They are both using prompts. The latter one is using a prompt internally as well as in the `typer.Option` call. In my mind, this is nice because it is a command that explicitly should never be automated. A user needs to make a conscious decision here and this is a nice safety mechanism. 

But ... I do like being able to unit-test this. So I've also gotten some unit tests. 

```python
# typertest.py
from typer.testing import CliRunner

from typermain import app

runner = CliRunner()


def test_db_cmd():
    # Note that we need to confirm here!
    result = runner.invoke(app, ["db", "create"], input="foobar\nfoobar\n")
    assert result.exit_code == 0
    assert "foobar" in result.stdout


def test_db_cmd2():
    # Note that we need to confirm here!
    result = runner.invoke(app, ["db", "delete", "--table", "foobar"], input="\n")
    assert result.exit_code == 0
    assert "foobar" in result.stdout
```

The `test_db_cmd` test runs fine, but the `test_db_cmd2` just hangs there. I'm thinking that the `input` that I pass in the `invoke` command isn't passed to the `typer.confirm("Are you really sure?")` inside of `delete_db`. 

Is there a way to pass this through? The docs clearly mention that calling `typer.confirm` internally isn't preferable, but I'm wondering if this is the reason why.

**Comment by daddycocoaman** [comment]
Hey @koaning, just want to say first how dope your calmcode site is. I learned a lot about rich and mkdocs from it, so thanks!

As for your question, I'm pretty new to pytest but I think I have an answer. But first, I had to change your code around a bit because it won't work as written (i.e., the arguments to runner.invoke() are invalid here).

The following code will pass the tests, but only if the rich.console is written with a local scope https://github.com/tiangolo/typer/issues/196#issuecomment-743752654 . Basically, it "patches" `typer.confirm` to return a True value for the test, therefore you won't need the `input` argument either. So you could make a True test and a False test if you needed.

```python
#test_typertest.py
from typer.testing import CliRunner
from typertest.main import app
from unittest import mock

runner = CliRunner()


def test_db_cmd():
    # Note that we need to confirm here!
    result = runner.invoke(app, ["create-db"], input="foobar\nfoobar\n")
    assert result.exit_code == 0
    assert "foobar" in result.stdout


@mock.patch("typer.confirm")
def test_db_cmd2(mock_typer):
    # Note that we need to confirm here!
    mock_typer.return_value = True
    result = runner.invoke(app, ["delete-db", "--table", "foobar"], input="\n")
    assert result.exit_code == 0
    assert "foobar" in result.stdout
```
```python
#typertest.main.py
from typing import List

import typer
from rich.console import Console

app = typer.Typer()
console = Console()

@app.command()
def create_db(table: str = typer.Option(..., prompt="What is the name of the table?", confirmation_prompt=True)):
    console.print(f"Creating table in database {table}", style="green")


@app.command()
def delete_db(table: str = typer.Option(..., prompt="What is the name of the table?", confirmation_prompt=True)):
    console = Console()
    sure = typer.confirm("Are you really sure?")
    if sure:
        console.print(f"Deleting table in database {table}", style="red")
    else:
        console.print(f"Back to safety!", style="green")


if __name__ == "__main__":
    app()
```

The real mystery is why the first command works with no problem but the second one needs that local rich.console(). 🤔

**Comment by koaning** [comment]
Good thing to know. Thanks! 

ps. This was a question I had in prerparation for the typer course. Happy to hear you like o code calmly 😄

**Comment by tiangolo** [comment]
Thanks for the help here @daddycocoaman! 🍰 

And thanks for coming back to close the issue @koaning ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
