### ISSUE TITLE
[QUESTION] ModuleNotFoundError: No module named typer 

### ISSUE THREAD

**Issue by scheung38** [tiangolo/typer#211]
### Description sample.py

```
import typer

def main(name: str):
    typer.echo(f"Hello {name}")


if __name__ == "__main__":
    typer.run(main)

```

python3 sample.py
Traceback (most recent call last):
  File "$HOME/sample.py", line 1, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
 

Is it possible that python versions again pip3's python not being the same?

### Additional context
(.venv) python3 --version
Python 3.9.1

(.venv) pip3 --version
pip3 --version
pip 20.3.3 from $HOME/.venv/lib/python3.8/site-packages/pip (python 3.8)
 

(.venv) pip3 list
Package         Version
--------------- -------
click           7.1.2
numpy           1.19.4
pandas          1.1.5
pip             20.3.3
python-dateutil 2.8.1
pytz            2020.4
setuptools      51.0.0
six             1.15.0
typer           0.3.2
wheel           0.35.1

Mac OSX: 11.1

**Comment by malthunayan** [comment]
@scheung38 seems like you have an issue with your pip installation pointing to a different path than your python version. Could you please try and see if using venv as a module works? In your case create an environment using the following command `python3 -m venv env` you can replace the last `env` with whatever you wanna call your environment. Then run `source path/to/env/bin/activate` (most likely this would just be `source env/bin/activate`, assuming you are in your project directory and have not changed directories). Finally install your dependencies as follows `python3 -m pip install <dependency>` as opposed to using `pip` directly. See if that resolves your issue, if that does then that means you have something weird going on with your python and pip installations, I'd recommend doing a clean reinstallation. Please let me know if that resolves your issue, if not I'd be happy to help out.

**Comment by scheung38** [comment]
@malthunayan thanks it seems better now:

python3 -m venv env_aa
source env_test/bin/activate

(env_aa) python3 --version
Python 3.9.1

(env_aa) pip3 --version
pip 20.2.3 from $HOME/env_aa/lib/python3.9/site-packages/pip (python 3.9)

(env_aa) ➜  pip3 install typer                                                                               
Requirement already satisfied: typer in ./env_aa/lib/python3.9/site-packages (0.3.2)
Requirement already satisfied: click<7.2.0,>=7.1.1 in ./env_aa/lib/**python3.9**/site-packages (from typer) (7.1.2)

(env_aa) ➜  python sample.py  
Usage: sample.py [OPTIONS] NAME
Try 'sample.py --help' for help.

Error: Missing argument 'NAME'.
(env_aa) ➜  python sample.py John
Hello John

Great thanks so this python not matching pip version.... still just began workin with Typer and not yet fully understood its powers yet!

**Comment by malthunayan** [comment]
@scheung38 you're most welcome! I'm glad I could be of help, and good luck with building your first typer app 🎉

**Comment by scheung38** [comment]
are you on Python Developers Slack channel now? Like to ask about Dataframes...

**Comment by malthunayan** [comment]
@scheung38 I'm not sure which Slack channel you are talking about, I'd just joined two python channels right now (pyslackers, and the python community Slack channel from heroku). You can reach me there if you see me (`malthunayan`), otherwise send me an invite to the workspace you are talking about.

**Comment by scheung38** [comment]
https://pythondev.slack.com/archives/C07EFMZ1N
![Screenshot 2020-12-22 at 22 06 14](https://user-images.githubusercontent.com/1273014/102937373-e9ed5280-44a1-11eb-99c7-1c19f0d12dab.png)

**Comment by tiangolo** [comment]
Thanks for the help here @malthunayan! :bow:
