### ISSUE TITLE
[QUESTION] How can I parse an optional argument with arbitrary number of values?

### ISSUE THREAD

**Issue by romankempt** [tiangolo/typer#212]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I parse an optional argument with arbitrary number of values?

### Additional context

In argparse, the function I have been using is:
```
    parser.add_argument(
        "-j",
        "--jobs",
        nargs="+",
        help="""List of task(s) to perform.""",
        type=str,
        default=["None"],
        dest="jobs",
    )
 ```

In typer, I've tried something like this:
```
    tasks: Optional[List[str]] = typer.Option(
        ["None"],
        "-j",
        "--jobs",
        help="Tasks to perform.",
    ),
```

Which will raise a TypeError:
```
TypeError:
It would appear that nargs is set to conflict with the composite type arity.
```

What I would like to achieve is a CLI option like this:
```
python main.py -j task_1 task_2 task_3
```

And in the main() function essentially something like this is done:
```
if "task_1" in jobs:
    do_that()
elif "task_2" in jobs:
   do_this()
   ...
```

**Comment by codethief** [comment]
I think the `TypeError` you're mentioning is due to this bug -> https://github.com/tiangolo/typer/issues/194

**Comment by romankempt** [comment]
I think I found the issue. Something like this works to some extent:

```
    tasks: Optional[List[str]] = typer.Option(
        None, "-j", "--task", help="Tasks to perform."
    ),
```

If one invokes the command one has to specify each option with a separate flag:
```
command -j task1 -j task2 -j task3
```

It's not perfect, but works for now.

**Comment by tiangolo** [comment]
Great! If that solves the original problem, then you can close this issue ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
