### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by david-shiko** [tiangolo/typer#214]
Problem:

`Unresolved attribute reference 'email' for class 'OAuth2PasswordRequestForm'`

The solution:

Make field `username` `Union`, `EmailStr` or `str`   `OAuth2PasswordRequestForm`  in `fastapi/security/oauth2.py` module.

Context:
`  # form_data.email not exists, only form_data.username`
`user = authenticate_user(crud.get_user_by_email(c), form_data.username, form_data.password)`

**Comment by daddycocoaman** [comment]
Wrong repo, fam.

**Comment by tiangolo** [comment]
Thanks for the help here @daddycocoaman ! 👏  🙇 

Thanks for reporting back and closing the issue @david-shiko  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
