### ISSUE TITLE
[QUESTION] Default datetime must be string (bug in older versions of Click)

### ISSUE THREAD

**Issue by aguinane** [tiangolo/typer#215]
### Describe the bug

When specifying a default value for an option of type datetime, it will throw a TypeError. 
You need to instead provide a string as click expects a string from the CLI and tries to convert it. 

### To Reproduce

Modifying the [datetime example](https://typer.tiangolo.com/tutorial/parameter-types/datetime/) slightly:

```Python
from datetime import datetime

import typer


def main(birth: datetime = datetime(2021, 1, 1)):
    typer.echo(f"Interesting day to be born: {birth}")
    typer.echo(f"Birth hour: {birth.hour}")


if __name__ == "__main__":
    typer.run(main)
```

* Call it with:

```bash
python main.py 1956-01-31T10:00:00
```

* It outputs:

```
 File "\venv\lib\site-packages\click\types.py", line 246, in convert
    dtime = self._try_to_convert_date(value, format)
  File "\venv\lib\site-packages\click\types.py", line 239, in _try_to_convert_date
    return datetime.strptime(value, format)
TypeError: strptime() argument 1 must be str, not datetime.datetime
```

### Environment

* OS: Windows
* Typer Version: 0.3.2
* Python version: 3.8

### Additional context

It works if you specify a string as the default value instead. But this causes mypy to be unhappy as you are assigning a value of the wrong type. It would be worth either calling this out in the documentation, or adding an additional check before sending the value to click for conversion to see if it's already a datetime.

**Comment by alexreg** [comment]
This has been fixed in more recent versions of Click.

**Comment by tiangolo** [comment]
Thanks for reporting it! :nerd_face: 

And thanks @alexreg for the help. :bow: 

It seems this is now fixed in Click. I just tried your example and it seems to work correctly now.  So it shouldn't need anything else here, right?

**Comment by aguinane** [comment]
yep working now.
