### ISSUE TITLE
[FEATURE] Typer steps with `typer.step`

### ISSUE THREAD

**Issue by lsorber** [tiangolo/typer#217]
Commands are often a series of steps with some logging around them to inform the CLI user of the progress. It would be nice to be able to write commands as a series of context-managed steps where `typer.step` takes care of printing the step, a spinner to indicate activity on the step, and finally printing the done symbol:

```python
@app.command()
def mycommand(file: Path):
    with typer.step(icon="👉", step=f"Reading {file}..."):
        do_something()
        do_something_else()
    with typer.step(icon="📦", step=f"Extracting data..."):
        do_work()
        do_more_work()
```

Example output could look like:

> 👓 Reading data.zip... ✅
> 📦 Extracting data... ✅
> 🏃 Reticulating splines... ✅
> 🔮 Crystal gazing... ✅
> ✍️ Writing output... /

Implementation of this feature could be as simple as:

```python
from contextlib import contextmanager
from typing import Iterator
import click_spinner

@contextmanager
def step(step: str = "", icon: str = "👉", done: str ="✅", error: str = "😵") -> Iterator[None]:
    print(f"{icon} {step} " if icon else f"{step} ", end="", flush=True)
    with click_spinner.spinner():
        yield
    print(done, flush=True)
```

The above is just a very rough idea for an API for `typer.step`, I'm sure it can be improved further.

**Comment by daddycocoaman** [comment]
This would be something interesting to implement with Rich's [status/progress modules.](https://github.com/willmcgugan/rich#status), especially since it comes with that emoji support.

**Comment by ssbarnea** [comment]
While I am interested about the same feature I should mention that from the UX point of view I find it more useful to display the result of the command at the beginning of the line, so they would be aligned and also to avoid using emoji for each action as this distracts the user and make it harder to read the output. Emoji are cool as long they are not overused. Usually if you endup having. more than 5-10 on an entire terminal window, it means they were overused.

Yep this means that the lines need to be rewritten when the status changes but that that is not a big deal.

**Comment by tiangolo** [comment]
Thanks for the discussion everyone! :coffee: 

Rich is now the recommended tool for displaying data, it's included if you install `typer[all]` and it's used internally, for example for the automatic help.

The docs now show how to use Rich by default: https://typer.tiangolo.com/tutorial/progressbar/

I think you could probably use it to show the information in steps, and it works better than `click_spinner` (even though I used and contributed to `click_spinner` before).

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by NikosAlexandris** [comment]
> While I am interested about the same feature I should mention that from the UX point of view I find it more useful to display the result of the command at the beginning of the line, so they would be aligned and also to avoid using emoji for each action as this distracts the user and make it harder to read the output. Emoji are cool as long they are not overused. Usually if you endup having. more than 5-10 on an entire terminal window, it means they were overused.
> 
> Yep this means that the lines need to be rewritten when the status changes but that that is not a big deal.

Would you have a working example ?
