### ISSUE TITLE
Combine type hinting with docstring ala Cleo

### ISSUE THREAD

**Issue by MRigal** [tiangolo/typer#218]
### Is your feature request related to a problem

No

### The solution you would like

The auto-generation of the CLI based on type hinting is fantastic, but having the possibility to add some more text/info would be great. I think the approach using docstring like in https://github.com/sdispater/cleo is an easy and good way to go.

Ideally, adding a docstring to any command would allow:

1. The first line (kind of resume) to be displayed in the help of the main application call
2. The content of the full docstring to be displayed in the help of the command call

Here is what the changes would be based on the Typer example:

```
// Check the --help
$ python main.py --help

Usage: main.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or customize the installation.
  --help                Show this message and exit.

Commands:
  goodbye                Say Goodbye with a smile          
  hello

// You have 2 subcommands (the 2 functions): goodbye and hello

// Now get the --help for hello

$ python main.py hello --help

Say goodbye with a smile.
Give the name of the person you want to say goodbye. See you!

Usage: main.py hello [OPTIONS] NAME

Arguments:
  NAME  [required]

Options:
  --help  Show this message and exit.
```

By modifying the script to:

```
@app.command()
def goodbye(name: str, formal: bool = False):
    """
    Say goodbye with a smile.
    Give the name of the person you want to say goodbye. See you!
    """
    if formal:
        typer.echo(f"Goodbye Ms. {name}. Have a good day.")
    else:
        typer.echo(f"Bye {name}!")
```

**Comment by daddycocoaman** [comment]
Isn't this already how it works?

```python
import typer

app = typer.Typer()


@app.command()
def hello(name: str, formal: bool = False):
    """
    Say hello with a smile.
    Give the name of the person you want to say hello. See you!
    """
    if formal:
        typer.echo(f"Hello Ms. {name}. Have a good day.")
    else:
        typer.echo(f"Bye {name}!")


@app.command()
def goodbye(name: str, formal: bool = False):
    """
    Say goodbye with a smile.
    Give the name of the person you want to say goodbye. See you!
    """
    if formal:
        typer.echo(f"Goodbye Ms. {name}. Have a good day.")
    else:
        typer.echo(f"Bye {name}!")


if __name__ == "__main__":
    app()
```

![image](https://user-images.githubusercontent.com/21189155/104770998-802e3480-573f-11eb-8d56-a6acb7cade29.png)
![image](https://user-images.githubusercontent.com/21189155/104771005-845a5200-573f-11eb-80e0-ed5bb27a7a07.png)

**Comment by tiangolo** [comment]
Thanks for the help @daddycocoaman! :bow: 

Yep, I think that's how it currently works. Is there anything else missing @MRigal?

**Comment by MRigal** [comment]
Hi @tiangolo and @daddycocoaman back then!

I somehow missed the answer at first time and now I changed computer, environment and everything to reproduce what I had/wanted at that time.

Therefore I can't confirm or infirm the point, maybe I oversaw something at that time. I'll close the issue as probably fixed and sorry for the noise. Great that it is working this way!
