### ISSUE TITLE
[QUESTION] Ability to call general processes

### ISSUE THREAD

**Issue by m1hawkgsm** [tiangolo/typer#222]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description
I've been using Typer for a while for my packages, to give it a nice CLI.  However, in a particular application, I need the ability to call processes, a la [Invoke](http://www.pyinvoke.org/), i.e.
```
   c.run("make build clean")
```

In the Typer documentation, I see limited support for opening up web browser and file explorer [here](https://typer.tiangolo.com/tutorial/launch/), but this isn't a full blown system process caller.

Is there any plans to boost the above capability to arbitrary system calls? Otherwise I might rely on a third party package such as [sh](https://github.com/amoffat/sh).

### Additional context

Above should be sufficient.

**Comment by daddycocoaman** [comment]
Would Typer invoking a shell command be anything more than a wrapper around `subprocess.run`? That's what [Invoke seems to do. ](https://github.com/pyinvoke/invoke/blob/008e93070540be5153a310d2794fb04b23f0194b/invoke/runners.py#L1271)

**Comment by m1hawkgsm** [comment]
Likely, but the benefit of Invoke is the API/design that is much more ergonomic than plain old `subprocess`. For what it's worth, I ended up using `sh` as its dynamic loading of shell functions "as python" is very user friendly.

I only asked about Typer potentially taking that route given it seems to have web browser and file explorer invocation already, which suggests there's the vision of it being a generalized CLI tool.

**Comment by alextremblay** [comment]
the web browser and file explorer / editor capabilities come from [click](https://click.palletsprojects.com/en/7.x/api/#utilities). If click were to also implement a generalized subprocess-handling utility, i could see typer someday wrapping that too, but i don't think it's something Typer should implement directly. It's a bit (in my opinion) beyond the scope of what Typer is designed for

But that's just my two cents

**Comment by tiangolo** [comment]
Thanks for the help here @daddycocoaman and @alextremblay ! 👏  🙇 

If that solves the original problem, then you can close this issue @m1hawkgsm  ✔️

And yep, I would rather explain how to use `subprocess`, that in recent versions of Python is so much better to use, rather than wrap it in another utility. Then people would end up having to learn both, so I would rather just explain how to use `subprocess` if anything. 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by m1hawkgsm** [comment]
That's fine, i kept using `sh` which i prefer ergonomically, works for me so will close, apologies i forgot about this!

**Comment by tiangolo** [comment]
Cool! Thanks for coming back to close the issue. ☕👍
