### ISSUE TITLE
mkdocs plugin for typer

### ISSUE THREAD

**Issue by bruce-szalwinski** [tiangolo/typer#228]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

I see that typer uses [mkdocs](https://www.mkdocs.org/) to generate its awesome documentation.  I also see that there is an extension to mkdoc for [click](https://github.com/DataDog/mkdocs-click) apps.  I tried pointing `mkdocs` at my typer application to generate documentation but ran into:

```
mkdocs_click._exceptions.MkDocsClickException: 'app' must be a 'click.BaseCommand' object, got <class 'typer.main.Typer'>
```

I was wondering if anyone had tried to write a mkdoc plugin for Typer.

**Comment by bruce-szalwinski** [comment]
Well, that wasn't too hard, https://github.com/bruce-szalwinski/mkdocs-typer.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
