### ISSUE TITLE
[FEATURE] Allow Arguments with alternative / custom names.

### ISSUE THREAD

**Issue by feluxe** [tiangolo/typer#230]
### Is your feature request related to a problem

Is your feature request related to a problem? Yes

In this example I'd like to use the name `id_` internally, but for the CLI I would like to provide an alternative name `id`:

```python
def user(id_: Optional[str] = typer.Argument(None)):
   ...
 ```

For Commands and Options, this is already possible using `@app.command("foo")` and `typer.Option(..., "--foo", "-f")`.

For Arguments it seems there is no way of doing this... if there was it would be nice to include a section for it in the docs, similar to [CLI Option Name](https://typer.tiangolo.com/tutorial/options/name/)

### The solution you would like

Maybe this:

```python
typer.Argument(None, "id")
```

or 

```python
typer.Argument(None, name="id")
```
?

**Comment by daddycocoaman** [comment]
You would use the `metavar` field:

```python
@app.command()
def print_id(id_: str = typer.Argument(..., metavar="id")):
    print(id_)
```

```
Usage: typerarg.py [OPTIONS] id

Arguments:
  id  [required]

Options:
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or
                        customize the installation.

  --help                Show this message and exit.
```

**Comment by feluxe** [comment]
Ah, thanks a lot!  I guess I was intuitively looking for it to have its own section. Commands and Options do have extra sections for this:

* Custom Command Name
* CLI Option Name

I didn't expect to find it in the `CLI Arguments with Help` section.

Just some feedback from someone new to typer :-)

Otherwise I'm really amazed by the project, same as `FastApi`. Both are such a joy to code with!

**Comment by tiangolo** [comment]
Thanks for the help here @daddycocoaman ! 👏  🙇 

If that solves the original problem, then you can close this issue @feluxe  ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
