### ISSUE TITLE
[FEATURE] Pass arbitrary objects to commands

### ISSUE THREAD

**Issue by ewjoachim** [tiangolo/typer#232]
### Is your feature request related to a problem

I'm a Click user. Most usually, in my Group function (or my Typer app callback ;) ), I'm bulding an object that I attach to `ctx.obj`, and my group commands use [`@click.pass_obj`](https://click.palletsprojects.com/en/7.x/api/#click.pass_obj)

As far as I can tell, there's no equivalent on Typer.

### The solution you would like

I'd like to leverage the typing system to receive the `ctx.obj` value as a command function parameter, and get benefits from my editor completion, as well as easier testing.

### Describe alternatives you've considered

While not 100% sure that would be the best solution, I would like to be able to assign my state object to ctx.obj, and when I request something of the corresponding type in my command function signature, receive the type.

```python

@dataclass
class MyState:
	a: int

app = typer.Typer()

@app.callback()
def main(a: int, ctx: typer.Context):
	ctx.obj = MyState(a=a)

@app.command
def sub(my_state: MyState):
	typer.echo(my_state.a)

```

Would that make sense ?

### Additional context

Any python function parameter of a type recognized as a standard CLI param (str, int, Path, ...) would take priority on checking ctx.obj

As of today, I can still use ctx.obj, it's just that it makes the code less readable and I don't get completion.

Possible addition: if ctx.obj is assigned a `Dict[Type, Any]`, then all commands requesting an object of type `Type` would get the corresponding value ? (Well, maybe it's too much, the aim is not to recreate a full dependency injection lib 😅).

If you're interested, I'll be glad to try doing a PR.

**Comment by inikolaev** [comment]
I would also like to be able to construct a more complex data class with nested data classes, e.g.:

```python
@dataclass
class SomeOtherState:
	value: int

@dataclass
class MyState:
	some_object: SomeOtherState
```

and then from the command line pass the value as `some_object.value=5`

**Comment by tiangolo** [comment]
The problem of the `ctx.obj` is precisely that it cannot be properly typed. Why do you need to do it via `ctx.obj`? Wouldn't a global variable work for your use case?

I know it's common to avoid global variables, but if it's only in the code for your CLI, then it's actually "local" to that command invocation.

And if you want to test it, you could create a function `def obtain_obj()` with an `@lru_cache` so that it always returns the same object, and you could type that, and you could mock it in testing if you needed to.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by ewjoachim** [comment]
Hey :) thanks for the answer.

I really dislike resorting to globals if it can be avoided. It makes everything more complicated. Also, relatedly, I do my best to avoid any kind of mocks, so...

I guess I'd rather use an untyped obj param than a typed global.

Thanks for your answer anyway.

**Comment by tiangolo** [comment]
Cool, get it. I imagine that answers the question, right? If that's the case, you could close the issue. 🤓

**Comment by kurtrwall** [comment]
In my opinion, this doesn't really resolve the question. I tried to assign a dataclass to the ctx.obj and am getting the following:

> RuntimeError: Type not yet supported

It's my configuration object and I do not want to have to pass in the constructive config values through every subcommand. It's much easier to set the config in one place and pass it down the command tree.

**Comment by elupus** [comment]
Workaround by subclassing the type context and constraining the obj type.

```python
@dataclass
class State:
    output: Path

class Context(typer.Context):
    obj: State

@app.callback(no_args_is_help=True)
def main(ctx: Context, output: Path):
   ctx.obj = State(output)
```

The typer.Context could be type defines as a generic type instead so we could do:

```
def main(ctx: typer.Context[State])
```
