### ISSUE TITLE
[BUG] Error: Got unexpected extra argument

### ISSUE THREAD

**Issue by prakashjayy** [tiangolo/typer#233]
## Describe the bug
`Error: Got unexpected extra argument` while calling a function using typer.

## Write here a clear and concise description of what the bug is.
I have specified 3 arguments for a function and getting the above error while using typer. my code looks like this. 

- main.py
```python
import typer 
app = typer.Typer()

@app.command()
def generate_csv(
    cfg: str,
    csv_loc: str,
    weights_locs: str,
):
    typer.echo(cfg)
    typer.echo(csv_loc)

if __name__ == "__main__":
    app()

```
- run `python infer.py generate-csv "xxx" "yyy" "lightning_logs/version_3/checkpoints/epoch=18-step=10164.ckpt"`

## Error 
```
Usage: infer.py [OPTIONS] CFG CSV_LOC WEIGHTS_LOCS
Try 'infer.py --help' for help.

Error: Got unexpected extra argument (lightning_logs/version_3/checkpoints/epoch=18-step=10164.ckpt)
```

however this error disappears and it works normally if I add another function as below and wrap it with typer. 

```python
```python
import typer 
app = typer.Typer()

@app.command()
def test():
    print("working fine")

@app.command()
def generate_csv(
    cfg: str,
    csv_loc: str,
    weights_locs: str,
):
    typer.echo(cfg)
    typer.echo(csv_loc)

if __name__ == "__main__":
    app()

```

- run `python infer.py generate-csv "xxxx" "yyyy" "lightning_logs/version_3/checkpoints/epoch=18-step=10164.ckpt"`

## output: 
```
xxxx  
yyyy
```

## Environment
- I am using `ubuntu 16.04` and Anaconda  python 3.6 environment. 
- I am using `typer==0.3.0`

**Comment by daddycocoaman** [comment]
When you only have one command, like in your first example, there is no need to specify the name of the command you want to run. Typer sees that you only have one command to run, therefore the user must be intending to run that command. 

So your first example should just be `python infer.py "xxx" "yyy" "lightning_logs/version_3/checkpoints/epoch=18-step=10164.ckpt"`

**Comment by prakashjayy** [comment]
Thanks @daddycocoaman.

**Comment by JavierLopezT** [comment]
> When you only have one command, like in your first example, there is no need to specify the name of the command you want to run. Typer sees that you only have one command to run, therefore the user must be intending to run that command.
> 
> So your first example should just be `python infer.py "xxx" "yyy" "lightning_logs/version_3/checkpoints/epoch=18-step=10164.ckpt"`

This should be on the first page of the documentation

**Comment by zhipengwa** [comment]
> > When you only have one command, like in your first example, there is no need to specify the name of the command you want to run. Typer sees that you only have one command to run, therefore the user must be intending to run that command.
> > So your first example should just be `python infer.py "xxx" "yyy" "lightning_logs/version_3/checkpoints/epoch=18-step=10164.ckpt"`
> 
> I don't think that's a good "design choice". Very confusing and weird. Why not support both cases when only 1 app.command wrapped func?

I want to second this comment, it costs me entire day to figure out the root cause.

**Comment by samibtorres** [comment]
I had the same problem for a while and found the page where it says if there is only one command defined in the app, but still want to use its name, there needs to be a callback defined : https://typer.tiangolo.com/tutorial/commands/one-or-multiple/

**Comment by zanieb** [comment]
It'd be great so support both cases e.g. `my_app` and `my_app my_command`, I also was very confused by this during development of a prototype application.

**Comment by nguyenvulong** [comment]
I just learned `Typer` half an hour ago and found 2 terrible designs
- automatic conversion from underscore to hyphen (inherited from `Click`)
- this. Should have let us use `python main.py func opt` in case there's a single command.

I guess if I find one more I'll stop using it because it's quite annoying.

**Comment by BrianPugh** [comment]
@nguyenvulong please open up an issue in the cyclopts repo for the first point; we can probably figure something out. Thanks!

**Comment by hariprasath2411** [comment]
Error: Got unexpected extra argument (serve)


FROM python:3.8-slim

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    build-essential \
    libsm6 \
    libxext6 \
    libxrender-dev \
    awscli \
    && rm -rf /var/lib/apt/lists/*

# Install PyTorch and other Python dependencies
RUN pip install torch==1.10.0 torchvision==0.11.1 cython pyyaml>6.0

# Install Detectron2 from source
RUN pip install 'git+https://github.com/facebookresearch/detectron2.git'

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the application code into the container
COPY inference.py /app/

# Install uvicorn
RUN pip install uvicorn

# Set the entry point for the container
ENTRYPOINT ["uvicorn", "inference:app", "--host", "0.0.0.0", "--port", "8080"]
