### ISSUE TITLE
[QUESTION] Autocomplete in poetry sub-shell?

### ISSUE THREAD

**Issue by boonhapus** [tiangolo/typer#236]
* [ X ] I used the GitHub search to find a similar issue and didn't find it.
* [ X ] I searched the Typer documentation, with the integrated search.
* [ X ] I already searched in Google "How to X in Typer" and didn't find any information.
* [ X ] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Is it possible to get autocomplete working in a poetry shell environment? My platform is windows, I've confirmed that I can autocomplete on a simple CLI app if I install `typer-cli` globally and run `--install-completion`, but trying those same steps after activating `poetry shell` returns the general error telling me `Shell cmd is not supported.`.

**Comment by tiangolo** [comment]
You should use PowerShell instead of CMD (in general).

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
