### ISSUE TITLE
[QUESTION] Passing a list to a CLI option?

### ISSUE THREAD

**Issue by FollowTheProcess** [tiangolo/typer#238]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Is it possible to pass a list to a typer.Option without having to do something like:

```shell
$ app argument --option thing1 --option thing2 --option thing3
```

i.e. is there a way to make it do:

```shell
$ app argument --option thing1 thing2 thing3
```

And then use this list of "things" in logic later as a list?

### Additional context

I ran into this because I'm in the process of converting a lot of my shell automation into a CLI with typer (which I love by the way!). I'm trying to replace a bit of bash function that can automatically create virtual environments for me and install packages if I pass a list of them (particularly useful for conda where you can specify packages at create time and they are all dependency resolved together for example).

I have a command that resembles the below snippet:

``` python
from typing import List

import typer

app = typer.Typer()


@app.command()
def say(
    initial_thing: str = typer.Argument(
        ..., help="This thing will be first to be said."
    ),
    other_things: List[str] = typer.Option(
        None,
        "--other",
        "-o",
        help="This thing should be a list of words.",
    ),
) -> None:
    """
    Say a thing, followed by an optional number of other things.

    Examples:

    $ python main.py hello --other these are some more space separated words to say
    """

    if other_things:
        typer.echo(f"{initial_thing} {other_things}")
    else:
        typer.echo(f"{initial_thing}")



if __name__ == "__main__":
    typer.run(say)
```

Here you can imagine the words passed to `--other` being a space-separated list of packages to install.

So ideally I could use this as in:

``` shell
$ python main.py hello --other some more things

# Ideal output...
$ hello some more things
```

However when I try this I get the following error:

<img width="844" alt="Screenshot 2021-02-24 at 09 19 25" src="https://user-images.githubusercontent.com/62767721/108978467-850ccf00-7681-11eb-8699-83078ce8175e.png">

Which makes total sense to me as it is only taking the next immediate thing after the `--other` as the option.

I know you can use a tuple to pass multiple values in this way, but the problem is the number of items following `--other` could vary wildly and my understanding is that with the tuple approach, it must be a fixed number of items.

Can anyone point me in the right direction?

Thanks!

**Comment by QuestofIranon** [comment]
Also interested (found this issue while searching for how to do this)

**Comment by dreamgonfly** [comment]
Also interested

**Comment by teauxfu** [comment]
Not sure about `Option`s, but it seems you can do this with `Argument`s
https://typer.tiangolo.com/tutorial/multiple-values/arguments-with-multiple-values/

**Comment by FollowTheProcess** [comment]
I've actually found a bit of a work around by using the context and `"allow_extra_args` then just collecting these args and using as originally intended.

See the docs here: https://typer.tiangolo.com/tutorial/commands/context/
