### ISSUE TITLE
[FEATURE] Beautify string option empty default value 

### ISSUE THREAD

**Issue by baterflyrity** [tiangolo/typer#242]
Hi! As you can notice from [tutorial](https://typer.tiangolo.com/tutorial/first-steps/) when defining empty string value for option it is documented like this:
>Options:
>  --lastname TEXT         [default: ]

So I suggest to beautify this output to something like this:
>Options:
>  --lastname TEXT         [default: empty]

### Full example
```python
import typer


def main(name: str, lastname: str = "", formal: bool = False):
    if formal:
        typer.echo(f"Good day Ms. {name} {lastname}.")
    else:
        typer.echo(f"Hello {name} {lastname}")


if __name__ == "__main__":
    typer.run(main)
```
>$ python main.py --help
>Usage: main.py [OPTIONS] NAME
>
>Arguments:
>  NAME  [required]
>
>Options:
>  --lastname TEXT         [default: ]
>  --formal / --no-formal  [default: False]
>  --install-completion    Install completion for the current shell.
>  --show-completion       Show completion for the current shell, to copy it or customize the installation.
>  --help                  Show this message and exit.

**Comment by baterflyrity** [comment]
Sure. Thanks for fix and also for new help table.
![изображение](https://user-images.githubusercontent.com/15788974/201880993-0a47f12f-d83f-4b8b-856c-07bc3e64cfc3.png)

**Comment by tiangolo** [comment]
Great! Thanks for coming back to close the issue.
