### ISSUE TITLE
[QUESTION] Order of multiple commands

### ISSUE THREAD

**Issue by ChristianMichelsen** [tiangolo/typer#246]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I define the order of the commands when writing a CLI with Typer with multiple commands? 

E.g. when I define the following minimal example with the two commands `cli_b` and `cli_a`:
  
  ``` python
# cli_test.py
import typer

cli = typer.Typer()

@cli.command()
def cli_b():
    typer.echo("cli_b")


@cli.command()
def cli_a():
    typer.echo("cli_a")

if __name__ == "__main__":
    cli()
  ```
  
and run `python cli_test.py`, I get:

``` bash
Usage: cli_test.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or
                        customize the installation.

  --help                Show this message and exit.

Commands:
  cli-a
  cli-b
```
Notice that Typer automatically re-orders the commands alphabetically (independently of the order in which they were defined). A similar thing happens when I define the names manually:

```python
# cli_test2.py
import typer

cli = typer.Typer()

@cli.command("b")
def cli_b():
    typer.echo("b")

@cli.command("a")
def cli_a():
    typer.echo("a")

if __name__ == "__main__":
    cli()
```

Is there any way to define the order in which the commands are shown in the terminal manually?

**Comment by daddycocoaman** [comment]
Click keeps the commands in a `dict` underneath, but as of Python 3.6, dicts remember insertion order (so essentially acting as an OrderedDict). So with that logic, you could do something like overwrite the `list_commands` of a Click group.

```python
import typer
import click
from click import Context
from typing import Iterable

class OrderedCommands(click.Group):
    def list_commands(self, ctx: Context) -> Iterable[str]:
        return self.commands.keys()

cli = typer.Typer(cls=OrderedCommands)

@cli.command(help="Command B!")
def cli_b():
    typer.echo("cli_b")

@cli.command(help="Command C!")
def cli_c():
    typer.echo("cli_c")

@cli.command(help="Command A!")
def cli_a():
    typer.echo("cli_a")

if __name__ == "__main__":
    cli()
```

**Comment by ChristianMichelsen** [comment]
Ah, perfect, @daddycocoaman, that works! Thanks for the quick response.

**Comment by ilya-kolpakov** [comment]
As of typer 0.6.1 the solution above results in `AssertionError`, but the solution here https://github.com/tiangolo/typer/issues/428#issuecomment-1238866548 works.
