### ISSUE TITLE
[QUESTION] Project maintenance status

### ISSUE THREAD

**Issue by ssbarnea** [tiangolo/typer#248]
I read about Typer and i really loved the docs, especially the bits explaining why and comparisons with other tools.

Now, looking at the current status of the repository and seeing that last change was over 8 months ago, combined with a list of pull requests that did not receive any review, even if they seem to be green, I cannot refrain from asking:

* What is the current maintenance status of the project?
* Does this project has any other core contributor than yourself?
* Have you configured a successor for your github account,.. in case something bad happens with you?

I hope you are not offended by these questions, probably you already know well how costly it for any developer to endup with a dependency that transforms into a liability.

TBW, I may also suggest enabling github "discussions" feature, in order to declutter the issue tracker. I had a very good success in keeping the questions separated from bugs while using it on several projects.

**Comment by daddycocoaman** [comment]
I've asked him on Twitter and the general response is: https://twitter.com/tiangolo/status/1367100380916629504

**Comment by tiangolo** [comment]
I think I had probably answered this before, and released several versions after this was posted, but yeah, I have a lot of additional plans for Typer. :rocket: 

* What do you exactly mean by the *maintenance status*?

Most of the maintenance work is reviewing PRs and answering questions in issues. That's something I have to certainly do more and spend more time on it.

And I could use help with all that!

* What do you mean with "core contributor"?

If you mean other people that have made PRs and commits, yes, there are.

If you mean others helping do the maintenance work of reviewing PRs to check if they are correct, implement tests, add the right docs, etc. unfortunately there are not a lot of people coming to help.

But for example, @daddycocoaman has been a tremendous help here answering questions from others. :bow: :coffee: 

* Have you configured a successor for your github account,.. in case something bad happens with you?

Yep, of course, don't worry. :nerd_face:  And there are also people with commit rights to my repos, even though they normally don't have much time to help a lot, but still, this won't get locked in some way if I die (still, please don't kill me).

About the issues vs discussions, I would love to move questions over there, but I need them to support templates first: https://github.com/community/community/discussions/2838

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
