### ISSUE TITLE
[QUESTION] Limit of characters in paremter : 4095. Could it be extended?

### ISSUE THREAD

**Issue by gardnerdev** [tiangolo/typer#249]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I pass long string (secret token) as an argument? The maximum length I can use is only 4095characters

Is it possible to to extend the limit?
Is there any workaround for that?

**Comment by gardnerdev** [comment]
@tiangolo could you help here? I tried using both arguments and options in interactive mode. Only argument in `--secret` manner is working but need to wait pretty long time to paste it. That's why prefer interactive mode

**Comment by daddycocoaman** [comment]
The max size for a string is 4095, and it's likely your terminal does not read more than that size on input. For Linux, try running `stty -icanon` but you might have to switch it back at some point to get the normal operation.

**Comment by tiangolo** [comment]
Thanks for the help @daddycocoaman! And thanks for closing the issue @gardnerdev, I imagine you found a solution. 🎉 

> Sorry for the long delay! 🙈  I wanted to personally address each issue and they piled up through time, but now I'm checking each one in order.
