### ISSUE TITLE
[Question] Use other examples in Building a Package that does not relate to weapon/gun/violence

### ISSUE THREAD

**Issue by Mariatta** [tiangolo/typer#251]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

In the "Building a Package" [tutorial](https://typer.tiangolo.com/tutorial/package/), the example package being built is a Portal Gun and one of the CLI command is to shoot, assuming with a "virtual" portal gun.

Would you consider changing these examples to something that doesn't remind folks of violence? I do appreciate that the examples are more concrete than "foo" or "bar". And I think it would be even better if it is not related to guns or weapons which could remind folks of violence.

Thank you for considering.

### Additional context

Perhaps instead of a shooting range or a gun, you could use a "music studio", and with commands are "record", or "stream" or something like that.

**Comment by mrqt0** [comment]
I am pretty sure the "portal gun" refers to a device to create a portal into another dimension from the series Rick and Morty, see https://rickandmorty.fandom.com/wiki/Portal_Gun. This is evident from the name "Rick" in the example. There seems to be no violence involve apart from the connotation of the word "gun". Are you aware of this, and if not would it change your opinion?

**Comment by tiangolo** [comment]
Thanks @Mariatta, but yeah, it's not something related to violence, it's a reference to the show "Rick and Morty". A portal gun is a gun that shoots portals to move between dimensions. It's a tool, just like a "drill gun".

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
