### ISSUE TITLE
[QUESTION] Autocompletion not working with --help (option not recognized)

### ISSUE THREAD

**Issue by ferreteleco** [tiangolo/typer#253]
### First check

* [X ] I used the GitHub search to find a similar issue and didn't find it.
* [X] I searched the Typer documentation, with the integrated search.
* [X] I already searched in Google "How to X in Typer" and didn't find any information.
* [X] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I configure Typer in order to enable autocompletion not only for my user defined option flags but also for --help option?

I'm already able to autocomplete custom options (--verbose / -- no-verbose, for example), but --help, --install-completion and --show-completion can't be autocompleted.

### Additional context

I'm using Typer in python 3-7-3.9 with zsh (oh-my-zsh) in ubuntu 20.04.

**Comment by svlandeg** [comment]
Hi! I know this is an old thread, and I apologize for the late follow-up.

I just double checked this with a `zsh` shell and the current version of Typer (0.12.3) and autocompletion for `--help`, `--install-completion` and `--auto-completion` actually does work now, so I'll go ahead and assume this is fixed and close this thread.
