### ISSUE TITLE
[QUESTION] How to dynamically add commands with typer?

### ISSUE THREAD

**Issue by ssbarnea** [tiangolo/typer#257]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

I am writing a CLI tool that would expose various commands available that are dynamically created and I need a method for adding commands when the app starts as they depend on the tool config, for example when run inside a different repository it may expose a different set of commands.

### Additional context

While using click in the past I was able to create some extra commands but I discovered that I was not able to change their description because the `__doc__` is static and python does not allow me to update it after the object are created.

**Comment by captainCapitalism** [comment]
Would something like that do:

Given `dynamic.json`
```json
{
  "first-command": true,
  "second-command": true,
  "second-command-name": "my-name",
  "second-command-help": "This is dynamic description."
}
```

and `dynamic_cli.py`
```python
import typer
import json

with open('dynamic.json', 'r') as j:
    config = json.load(j)

app = typer.Typer()


def say_hello():
    typer.echo("HELLO")


def say_goodbye():
    typer.echo("BYE")


if config["first-command"]:
    app.command()(say_hello)

if config["second-command"]:
    say_hello.__doc__ = config["second-command-help"]
    say_hello.__doc__ += " 5546"

    app.command(
        name=config["second-command-name"],
    )(say_goodbye)

if __name__ == "__main__":
    app()
```

You can configure what is exposed by the CLI. You could also use `app.command(hidden=True)`, however it just hides the command from help - you could still call it.

Or your use case is more complex and you are looking for some more sophisticated solution?

**Comment by ssbarnea** [comment]
@captainCapitalism Thank you! The example seem to be sufficient for my use-case. I am going ot test it this evening. I was about to avoid click completely for this new tool due to the complications related to docs and dynamic commands.

I will close it, eventually reopening if it does not work.

**Comment by captainCapitalism** [comment]
To add to this `app.command()` has `help` argument, so you can pass any string to it from configuration to the same effect as `__doc__`.
```
@app.command(help="my custom help message")
def some_command()
...

```

**Comment by tiangolo** [comment]
Thanks for the help here @sathoune ! 👏  🙇 

Thanks for reporting back and closing the issue @ssbarnea  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by choucavalier** [comment]
hello! how can we also dynamically add arguments to the command? i'm trying to generate a typer CLI programmatically

**Comment by jeffswt** [comment]
@choucavalier Just change the signature

```py
import inspect
import typer


app = typer.Typer()

@app.command()
def run() -> None:
    return

def _wrapper(**kwargs) -> None:
    print(kwargs)
    return

_wrapper.__name__ = "dynamic_command"
_wrapper.__signature__ = inspect.Signature(  # type: ignore
    parameters=[
        inspect.Parameter(
            name="the_argument_name",
            kind=inspect.Parameter.KEYWORD_ONLY,
            default="DefaultValue",
            annotation=str | None,
        ),
    ],
    return_annotation=None,
)

app.command()(_wrapper)


if __name__ == "__main__":
    app()
```

Results:

```
$ python ./test.py dynamic-command --help

 Usage: test.py dynamic-command [OPTIONS]

╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --the-argument-name        TEXT  [default: DefaultValue]                                                 │
│ --help                           Show this message and exit.                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
