### ISSUE TITLE
[QUESTION] How to use Typer within Objects

### ISSUE THREAD

**Issue by PabloLec** [tiangolo/typer#261]
Hello,

I already used Typer for a few short CLIs but now I'd like to use it for a bigger, object-oriented project.
I thought I find a way to use it correctly, but I'm getting errors related to the "self" argument.

My code looks like this:

**main_menu.py**
```
class MainMenu:
    typer_app = typer.Typer()
    typer_app.add_typer(TournamentMenu.typer_app, name="tournament")

    def __init__(self):
        self.typer_app()
        self.tournament_handler = None
        self.print_menu()
        self.user_selection()

    def print_menu(self):
        number = typer.style("1. ", bold=True)
        typer.echo(number + "Tournois")

        number = typer.style("2. ", bold=True)
        typer.echo(number + "Gérer les joueurs")

    def user_selection(self):
        selection = typer.prompt("Entrez votre sélection: ")
        typer.echo("\n")

        if selection == "1":
            self.open_tournament_menu()
        else:
            self.user_selection()

    def open_tournament_menu(self):
        TournamentMenu()
```

**tournament_menu.py**
```
class TournamentMenu:
    typer_app = typer.Typer()

    def __init__(self):
        self.typer_app()
        self.print_menu()
        self.user_selection()

    def print_menu(self):
        number = typer.style("1. ", bold=True)
        typer.echo(number + "Commencer un nouveau tournoi")

        number = typer.style("2. ", bold=True)
        typer.echo(number + "Charger un tournoi")

    def user_selection(self):
        selection = typer.prompt("Entrez votre sélection: ")

        if selection == "1":
            self.create_new_tournament()
        else:
            self.user_selection()

    @typer_app.command("new")
    def create_new_tournament(self=None):
        NewTournamentMenu()
```

**new_tournament_menu.py**
```
class NewTournamentMenu:
    typer_app = typer.Typer()

    @typer_app.command()
    def __init__(self):
        self.typer_app()
        self.print_menu()
        self.user_selection()

    def print_menu(self):
        number = typer.style("1. ", bold=True)
        typer.echo(number + "Commencer un nouveau tournoi")

        number = typer.style("2. ", bold=True)
        typer.echo(number + "Charger un tournoi")

    def user_selection(self):
        selection = typer.prompt("Entrez votre sélection: ")

        if selection == "1":
            pass
        else:
            self.user_selection()
```

But for example with `python main.py tournament new`I'm getting:

```
Usage: dev.py [OPTIONS] SELF
Try 'dev.py --help' for help.

Error: Got unexpected extra argument (new)
```

So, is it possible to use typer in this kind of object oriented situation ? What am I missing ?

**Comment by captainCapitalism** [comment]
What are you trying to achieve by encapsulating commands into classes?

**Comment by PabloLec** [comment]
I'm trying to have a fully object oriented project. I would like the commands to serve as "shortcuts" for menus/sub-menus, and these menus are classes.
I could have typer related functions in an independant file that act as entry points to different parts of the program.
But, is there any way to encapsulate Typer commands inside classes ? The purpose would be avoiding the creation of "global" functions.

**Comment by SamuelBradley** [comment]
I would also like to know if there is a way to achieve this. I was able to do it with Click using a fairly complex pattern.
My goal its to define CLI functions in a base class and be able to extend it, so a typical polymorphism OO use case. 

It worked really well in my Click implementation but those annotation are ugly as sin and I would much prefer to use typer.

**Comment by captainCapitalism** [comment]
@SamuelBradley Could you provide some working example of this for Click? I could take some time to try to explore this.

**Comment by SamuelBradley** [comment]
OK Here is the utility code, I stumbled across this when searching for a similar solution specifically for Click. 

```python
class command:
    def __init__(self, name=None, cls=click.Command, **attrs):
        self.name = name
        self.cls = cls
        self.attrs = attrs

    def __call__(self, method):
        def __command__(this):
            def wrapper(*args, **kwargs):
                return method(this, *args, **kwargs)

            if hasattr(method, "__options__"):
                options = method.__options__
            return self.cls(self.name, callback=wrapper, params=options, **self.attrs)

        method.__command__ = __command__
        return method


class option:
    def __init__(self, *param_decls, **attrs):
        self.param_decls = param_decls
        self.attrs = attrs

    def __call__(self, method):
        if not hasattr(method, "__options__"):
            method.__options__ = []

        method.__options__.append(
            click.Option(param_decls=self.param_decls, **self.attrs)
        )
        return method


class Cli:
    def __new__(cls, *args, **kwargs):
        self = super(Cli, cls).__new__(cls, *args, **kwargs)
        self._cli = click.Group()

        # Wrap instance options
        self.__option_callbacks__ = set()
        for attr_name in dir(cls):
            attr = getattr(cls, attr_name)
            if hasattr(attr, "__options__") and not hasattr(attr, "__command__"):
                self._cli.params.extend(attr.__options__)
                self.__option_callbacks__.add(attr)

        # Wrap commands
        for attr_name in dir(cls):
            attr = getattr(cls, attr_name)
            if hasattr(attr, "__command__"):
                command = attr.__command__(self)
                # command.params.extend(_options)
                self._cli.add_command(command)

        return self

    def run(self):
        """Run the CLI application."""
        self()

    def __call__(self):
        """Run the CLI application."""
        self._cli()
```
This is the example of my base class to achieve my polymorphism use case, includes the command with options

``` python
import abc
from .utils import option, command, Cli

class BaseModule(abc.ABC, Cli):

    @abc.abstractmethod
    def run_job_logic(self, parameters: dict, files: Dict[str, FileRef]) -> Output:
        """
        This is the custom implementation of what will become an interface. Does the necessary setup
        to execute the existing module code. This method should represent 90% or more of the custom code
        required to create a module using pre existing logic.

        Arguments:
            parameters {dict} -- [description]
            files {dict} -- [description]
            output_path {str} -- [description]
        """
        pass


    @command("run-job")
    @option(
        "params_path",
        "--params-path",
        default=None,
        envvar="PARAMS_PATH",
        type=ClickPath(exists=True),
    )
    @option(
        "params_json", "--params-json", default=None, envvar="PARAMS_JSON", type=str
    )
    @option(
        "file_refs_json",
        "--files-json",
        default=None,
        envvar="FILE_REFS_JSON",
        type=str,
    )
    @option(
        "file_refs_path",
        "--files-path",
        default=None,
        envvar="FILE_REFS_PATH",
        type=ClickPath(exists=True),
    )
    @option(
        "input_path",
        "--input",
        default="input",
        envvar="FILES_IN_PATH",
        type=ClickPath(),
    )
    @option(
        "output_path",
        "--output",
        default="output",
        envvar="OUTPUT_PATH",
        type=ClickPath(),
    )
    @option("--zip", is_flag=True)
    def run_job(
        self,
        params_path,
        params_json,
        file_refs_json,
        file_refs_path,
        input_path,
        output_path,
        zip,
    ):
        ...
```
And for completeness here is an implementation module
``` python

class TestModule(BaseModule):
    def run_job_logic(self, parameters: dict, files: Dict[str, FileRef]) -> Output:
        ...


if __name__ == "__main__":
    TestModule().run()
```

**Comment by captainCapitalism** [comment]
@SamuelBradley Thanks! I will have a look and post the update.

**Comment by captainCapitalism** [comment]
@SamuelBradley I did some exploration and uploaded results here: https://github.com/captainCapitalism/typer-oo-example

I think main takeaway is that it is all good if you don't try to use `app.command` as a decorator and use it as function call instead. Let me know if that helps your case.

@PabloLec I know it will sound counterintuitive but I worked through your example and commented out all `typer.Typer()`'s and I think it works as you wanted it to. You can see here: https://github.com/captainCapitalism/typer-oo-example/tree/master/typer_example

If you want to use multiple typers check out the 'click_to_many_typers' from here: https://github.com/captainCapitalism/typer-oo-example/tree/master/click_to_many_typers that should help you.

**Comment by PabloLec** [comment]
Thanks @captainCapitalism for your help!

Indeed, my intention was to create multiple typer apps in order to compose CLI commands.

For my actual project I ended up using short functions, decorated with typer apps, instanciating my different objects. Thus, these short functions only act as entry points.

Your solution in `click_to_many_typers` is clever, I would have never think about that. But, if I understand correctly, in this configuration every "sub-commands" need to be explicitly declared as abstract methods in the BaseModule object. I guess this disallows having totally different commands in the different typer apps.
Nonetheless, that's a great idea. I might try to wrap my head around it for my current project. My initial goal was having a fully (maybe useless) OO typer app module. Idealy just creating one single class instancitating a typer app, encapsulating its sub-apps and sub-commands within methods. With your structure example I think it might be possible.

I think we can close this issue, if you agree @SamuelBradley.

**Comment by SamuelBradley** [comment]
Excellent example thank you. Yes I think this solves my use case nicely.

**Comment by captainCapitalism** [comment]
@PabloLec 
```Your solution in click_to_many_typers is clever, I would have never think about that. But, if I understand correctly, in this configuration every "sub-commands" need to be explicitly declared as abstract methods in the BaseModule object. I guess this disallows having totally different commands in the different typer apps.```
No, I don't think that's the case, I just fixated myself on the `ABC` from Samuel's example. I should be able to have a look later today.

**Comment by captainCapitalism** [comment]
@PabloLec I added two more examples.
1. [instance_app](
https://github.com/captainCapitalism/typer-oo-example/tree/master/instance_app
) where I initialize typer.Typer as you did in your original response and why it is not a good idea.
2. [many_tapers_extended](
https://github.com/captainCapitalism/typer-oo-example/tree/master/many_typers_extended
) with some custom methods not declared as abstract methods. There seems to be no problem to do so. You can also add groups of commands freely as you wish. And also now `PapaTyper` has initialization encapsulated in `__init__` rather than passed as an argument.

**Comment by PabloLec** [comment]
Thanks a lot ! That's exactly it :)

I'll definitly use it in future projects. Really clever way to do it, thank you again for your time !

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

Thanks for reporting back and closing the issue @PabloLec  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
