### ISSUE TITLE
[QUESTION] Is Typer abandoned?

### ISSUE THREAD

**Issue by JeppeKlitgaard** [tiangolo/typer#263]
Has Typer been abandoned/turned inactive?

To an outsider it seems like there are some perfectly good pull requests ready to merge and that there hasn't been any activity for around 8 months.

The reason I am asking is because I was hoping to use Typer in a project - It looks like an excellent library! I am a bit wary of doing that if the project is no longer maintained though.

**Comment by Atem18** [comment]
https://twitter.com/tiangolo/status/1375066666665672711?s=21

tl;dr He will soon resume work on FastAPI and Typer.

**Comment by JeppeKlitgaard** [comment]
@Atem18 

That looks very promising indeed! Thank you so much for pointing this out!

**Comment by tiangolo** [comment]
Nope, Typer is not abandoned, in fact, I just released Typer `0.4.0`, which is compatible with **both** Click 7 and Click 8. :tada:

But of course, it all depends on how much time I have available to dedicate to it.

A lot of my time is spent handling issues, replying to questions, etc. (here and in the other projects). 

If you would like to see faster progress, you could help by answering questions from others, sponsoring, etc. https://typer.tiangolo.com/help-typer/#help-others-with-issues-in-github
