### ISSUE TITLE
[Doc] How to test a typer CLI ? 

### ISSUE THREAD

**Issue by Leletir** [tiangolo/typer#27]
Hello,

First of all, thank you for your work, I'm a huge fan of FastAPI and my team is using Spacy everyday !
I'm trying to migrate my Click CLI to typer, and I was wondering how to test the CLI ?

**Comment by Leletir** [comment]
Fo those who where wondering, `typer` use the same mecanism as Click, just do: 
`from typer.testing import CliRunner`

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1: 

Just in case, here are the new docs for testing: https://typer.tiangolo.com/tutorial/testing/
