### ISSUE TITLE
[QUESTION] Is it possible to select options with the keyboard?

### ISSUE THREAD

**Issue by yogevyuval** [tiangolo/typer#276]
### First check

* [ ] I used the GitHub search to find a similar issue and didn't find it.
* [ ] I searched the Typer documentation, with the integrated search.
* [ ] I already searched in Google "How to X in Typer" and didn't find any information.
* [ ] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Is it currently possible to have a checkbox select, allowing a user to select options with the keyboard (up down to navigate, space to select). This is common in other cli tools, and looks something like this:

![image](https://user-images.githubusercontent.com/962869/116850682-bb267c00-abf9-11eb-9d74-fd45bca2b1ba.png)

**Comment by daddycocoaman** [comment]
You can just use Typer to invoke a library like [Questionary](https://questionary.readthedocs.io/en/stable/)

**Comment by tiangolo** [comment]
Thanks for the help here @daddycocoaman ! 👏  🙇 

If that solves the original problem, then you can close this issue @yogevyuval  ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
