### ISSUE TITLE
[BUG] No module name click._bashcomplete

### ISSUE THREAD

**Issue by sachindevsharma** [tiangolo/typer#278]
### Describe the bug

The latest version of **click** rolled out today 12/05/2021 and it doesn't have the _bashcomplete component. Can this be fixed .

I know I can use click==7.1.2, but that's a temporary workaround.

**Comment by kkirsche** [comment]
Not sure if `click.shell_completion.BashComplete` is the replacement — not familiar with the use in Typer today for this, but figured I'd mention it

**Comment by kkirsche** [comment]
Looks like it'll be more involved than 1:1 replacement, but certainly achievable

PR is useful to understand how the change works
https://github.com/pallets/click/pull/1622

Official Docs do well to expand upon that with concrete information:
https://click.palletsprojects.com/en/master/shell-completion/

**Comment by rehevkor5** [comment]
This also breaks https://github.com/openapi-generators/openapi-python-client

`pip install click==7.1.2` did not fix it.

**Comment by tiangolo** [comment]
Thanks for the discussion and interest! :cake: 

I just released Typer `0.4.0`, which is compatible with **both** Click 7 and Click 8. :tada:
