### ISSUE TITLE
[QUESTION] A selection menu?

### ISSUE THREAD

**Issue by cheetahbyte** [tiangolo/typer#295]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Good day to you all, 
can someone tell me how I can implement something like this in typer? I just can't find anything?
( If it is possible at all )
![grafik](https://user-images.githubusercontent.com/40123243/122963323-7364db00-d386-11eb-9889-26479ead5597.png)

**Comment by captainCapitalism** [comment]
Typer does not have it natively. You can search for some other packages that allow for interactive prompt and use them within typer. For example with `simple_term_menu` package.

```python
import typer
import simple_term_menu

app = typer.Typer()


@app.command()
def main():
    terminal_menu = simple_term_menu.TerminalMenu(["entry 1", "entry 2", "entry 3"])
    menu_entry_index = terminal_menu.show()
    typer.echo(f'You choose: {menu_entry_index}')

if __name__ == "__main__":
    app()
```

**Comment by cheetahbyte** [comment]
Thank you, that worked out great.
