### ISSUE TITLE
[QUESTION] How to reuse command line arguments?

### ISSUE THREAD

**Issue by lhayhurst** [tiangolo/typer#301]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Hi, I've scoured the docs but haven't found an answer to this question, so thought I'd come here. Apologies if I missed it in the docs! :/ 

I have four subcommands that all share the same 6 command line args (one argument, 5 options). I'd like to avoid copy-pasta'ing the same args four times. Is there a way to do this?

For example: 
```python
app = typer.Typer()

@app.command 
def doA( script: Path = typer.Argument(..., help="helptext"), 
               version: int = typer.Option(..., help="helptext",
               name: str = typer.Opton(..., help="helptext"),
               var: Optional[List[str]] = typer.Option([], help="helptext"):
    pass

@app.command 
def doB( script: Path = typer.Argument(..., help="helptext"), 
               version: int = typer.Option(..., help="helptext",
               name: str = typer.Opton(..., help="helptext"),
               var: Optional[List[str]] = typer.Option([], help="helptext"):
    pass

# the same, a few more times!
```

### Additional context

Trying to not get made fun of my by colleagues when I show them `typer` for the first time ;-) 

Cheers

**Comment by orensbruli** [comment]
Same situation. Need options common for several commands, like verbose, for example.

**Comment by graue70** [comment]
You could do this and re-use the variables for all subcommands:
```python
MY_ARGUMENT = typer.Argument(..., help="helptext")
MY_VERSION_OPTION = typer.Option(..., help="helptext")

@app.command 
def doA( script: Path = MY_ARGUMENT, 
               version: int = MY_VERSION_OPTION,
               name: str = typer.Opton(..., help="helptext"),
               var: Optional[List[str]] = typer.Option([], help="helptext"):
    pass
```

**Comment by lhayhurst** [comment]
Sorry for the late reply here! I think this issue can be closed, thank you :)
