### ISSUE TITLE
[FEATURE] --support for required arguments

### ISSUE THREAD

**Issue by sometato** [tiangolo/typer#303]
Let's say there's a CLI like this: `hosting-company launch-a-server some-hostname --days 90 --ssh-key-file ~/.ssh/id_rsa.pub` `--days` and `--ssh-key-file` are both required.

With typer, this would look like `hosting-company launch-a-server some-hostname 90 ~/.ssh/id_rsa.pub` which seems less grokable, especially in scripts.

Would it be doable to have --long-arguments for required fields? Doesn't necessarily have to show up in help, although it could.

**Comment by captainCapitalism** [comment]
I have a hard time trying to understand, what you would like to achieve. Would you provide some code samples with behaviour that you'd like to get (ex. What typer does now vs how you imagine it should work)?

**Comment by daddycocoaman** [comment]
Sounds like you're looking for required options.

https://typer.tiangolo.com/tutorial/options/required/

**Comment by sometato** [comment]
That's exactly what I meant/wanted. Thank you @daddycocoaman !
