### ISSUE TITLE
[QUESTION] How can I split my commands into different "command.py" files?

### ISSUE THREAD

**Issue by GrGohan** [tiangolo/typer#306]
### First check
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description
I am just getting started with the library Typer for building CLI's. I apologize in advance if this issue has been raised more than once, but I could not find it on Google to help me with the correct implementation.
There are too many commands in my cli.py and I want to moved them to a separate folder “commands”, but I cannot figure out how to implement a dynamic loader for these commands in cli.py. 
``` 
my_app/
 __init__.py
 commands/
       __init__.py
       command1.py
       command2.py
 cli.py
```
I want start by creating a class "Command" for each command with a single function "handle (**options)" that contains the functionality. But I am not sure if I am forming the class correctly. I want to make a class "AsyncCommand" because the command can be complex and can be properly decomposed into methods and encapsulated within one class
```
# a_test_command.py
from typer.core import TyperCommand
class AsyncCommand(TyperCommand):
    @staticmethod
    async def handle('a-test-command'):
        print('test_command')
```
Ideally, when starting cli.py, I want to check which modules are there and load them dynamically, leaving the cli.py file clean. But I do not understand at all how it is better and more correct to implement it.

**Comment by captainCapitalism** [comment]
Were you using subcommands already: https://typer.tiangolo.com/tutorial/subcommands/
or is your case different?

**Comment by GrGohan** [comment]
Yes, I figured it out, but I thought that me need to work with the class somehow differently than with a simple function, but there is no difference :)
But I still have a problem with how to organize the dynamic addition of the module, so as not to produce a lot of "app.add_typer (command)"
I mean something like:
```

**Comment by captainCapitalism** [comment]
Unless you mean to load commands based on argument supplied by the user, you could create for example dictionary in `commands.__init__.py`:
```python
from .command1 import command1
from .command2 import command2

all_commands = {
    "command1": command1,
    "command2": command2, 
}
```

and within your `main.py` or `cli.py`:
```python
import typer 

from commands import all_commands

app = typer.Typer()
for name, command in all_commands.items():
    app.add_typer(command, name=name)
```

I would advice against dynamically loading commands based on user's input because in case:
```bash
my-cli wrong-command
```

Typer would not load your command and help would probably be empty or you could get an error because it couldn't add not existing resource, forcing user to know what commands are available beforehand.

**Comment by captainCapitalism** [comment]
Actually you don't have to create a dictionary like this when you do pass a name for the subcommands, like:
```python
import typer
command1 = typer.Typer(name="command1")
```
so instead of a dictionary a list would also do:
`commands.__init__.py`
```python
from .command1 import command1
from .command2 import command2

all_commands = [
    command1,
    command2,
]
```
and in the `main.py`:
```python
import typer

from .commands import all_commands

app = typer.Typer()
for sub_command in all_commands:
    app.add_typer(sub_command)

```

**Comment by GrGohan** [comment]
Thank you very much for your help. I apologize in advance for this possibly stupid question, but how can I avoid this error?
```
File "/usr/local/lib/python3.7/site-packages/typer/main.py", line 347, in get_group_from_info
    for command_info in group_info.typer_instance.registered_commands:
AttributeError: module 'commands.healthcheck' has no attribute 'registered_commands'
```
My command module look like:
```
import typer
app = typer.Typer()

class Command:
    def __init__(self, *args):
        self.args = args

    @staticmethod
    @app.command()
    def handle():
        print('_' * 11)
        print('test_command')

if __name__ == "__main__":
    app()
```

**Comment by captainCapitalism** [comment]
The one who is stupid, gets stuck and never asks a question. :)

Could you add some more details?

I did run your code as a command and subcommand and it works for me.

![works-on-my-machine](https://user-images.githubusercontent.com/32553875/127548089-d8fee43f-3969-49b0-81d0-6f868100297f.png)

**Comment by GrGohan** [comment]
Thanks again for your help, you really helped me)
I added 5 and 22 lines from your code and it helped
