### ISSUE TITLE
[FEATURE] Adding Typer to custom package using entry points 

### ISSUE THREAD

**Issue by mr-bjerre** [tiangolo/typer#34]
Wuhuu finally started using Typer and very excited about it.

I went ahead and used the most simple example 

```python
import typer

def main(name: str):
    typer.echo(f"Hello {name}")


if __name__ == "__main__":
    typer.run(main)
```
which works just fine obviously. But I'd like to expose my custom package with CLI using Typer so I made a `setup.py` with 

```python
from setuptools import setup

setup(
    name="my_package",
    entry_points={
        "console_scripts": ["hello = my_package.cli:main"],
    },
)
```

Then I can call the command using `hello` in a terminal BUT it doesn't carry over any positional arguments. Maybe you could add some about entry points integration in the docs?

**Comment by mr-bjerre** [comment]
The entry points documentation should also cover the examples with `app = typer.Typer()` of course.

**Comment by mr-bjerre** [comment]
It seems using `app = typer.Typer()` and `@app.command()` works with entry points and positional arguments. Strange that its different?

**Comment by sander76** [comment]
Replace 'if __name__ == "__main__":' from your example with a function name. Like start.
Then use that function name in your entrypoint

**Comment by danielarnason** [comment]
> It seems using `app = typer.Typer()` and `@app.command()` works with entry points and positional arguments. Strange that its different?

@mr-bjerre How do the entry points in `setup.py` look like when using `app = typer.Typer()` and `@app.command()`? 

Is it something like `"console_scripts": ["hello = my_package.cli:app]`

**Comment by tiangolo** [comment]
Thanks for the discussion here everyone!

If you have simple scripts and you want to get completion, you can now use [Typer CLI](https://typer.tiangolo.com/typer-cli/) to run your Typer scripts without having to install anything.

If you want to create a package, there's a new guide [Building a Package](https://typer.tiangolo.com/tutorial/package/)  :tada: .

**Comment by vikahl** [comment]
Brilliant, thank you so much for this package!

**Comment by mr-bjerre** [comment]
I tried to use Typer CLI. Added the following to `my_package/main.py`

```python
import typer

app = typer.Typer()


@app.command()
def hello(name: str = None):
    if name:
        typer.echo(f"Hello {name}")
    else:
        typer.echo("Hello World!")


@app.command()
def bye(name: str = None):
    if name:
        typer.echo(f"Bye {name}")
    else:
        typer.echo("Goodbye!")


if __name__ == "__main__":
    app()
```

and then I ran 

    typer my_package.main run

from `my_package` directory but I get the following error

```python
Traceback (most recent call last):
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/bin/typer", line 10, in <module>
    sys.exit(main())
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/typer_cli/main.py", line 294, in main
    return app()
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/typer/main.py", line 211, in __call__
    return get_command(self)()
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/typer_cli/main.py", line 66, in invoke
    self.maybe_add_run(ctx)
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/typer_cli/main.py", line 71, in maybe_add_run
    maybe_add_run_to_cli(self)
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/typer_cli/main.py", line 144, in maybe_add_run_to_cli
    obj = get_typer_from_state()
  File "/home/nixd/PLX/ThirdpartyPublisher/venv/lib/python3.8/site-packages/typer_cli/main.py", line 128, in get_typer_from_state
    spec = importlib.util.find_spec(state.module)  # type: ignore
  File "/usr/local/lib/python3.8/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'my_package'
```

and I do have `my_package/__init__.py`

**Comment by mr-bjerre** [comment]
Ahh I just realized that I didn't add the root directory to `PYTHONPATH`

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue @mr-bjerre ! :cake: :+1:

**Comment by maartenq** [comment]
The entry_point should point so somthing executing  `typer.run`. Something like this would do:

```python
import typer

def main(name: str):
    typer.echo(f"Hello {name}")

def run():
    typer.run(main)

if __name__ == "__main__":
    run()
```

```python
from setuptools import setup

setup(
    name="my_package",
    entry_points={
        "console_scripts": ["hello = my_package.cli:run"],
    },
)
```

**Comment by paulofreitas** [comment]
By using `app = typer.Typer()` and `@app.command()` decorator on `main()` you can also use `app` as the entry point. 👍
