### ISSUE TITLE
Typer App with multiple commands: show help when called without a command.

### ISSUE THREAD

**Issue by lucacerone** [tiangolo/typer#369]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer

app = typer.Typer()

@app.command()
def command_1(arg:str):
  typer.echo(arg)

@app.command()
def command_2(arg:str):
  typer.echo(arg)


if __name__ == "__main__":
  app()
```

### Description

I would like to know if there's a way to make the "--help"  behaviour the default, in case the script is called with no command. 

For example (say the script above is `script.py`):

```bash
python script.py
```

shows an error, and invites to use `python script.py --help`. 

Can I make this the default behaviour (i.e. `python script.py --help` should be the same as `python script.py`).
I have been reading the documentation, and I suspect I might have to use a callback, though I don't quite understand how.

### Operating System

macOS

### Typer Version

0.4.0

### Python Version

3.8.2

**Comment by lucacerone** [comment]
I just discovered that I can achieve this with `no_args_is_help=True`. Closing.

**Comment by micouy** [comment]
For those searching how to do it:

```python3
app = typer.Typer(no_args_is_help=True)
```

**Comment by marcstreeter** [comment]
not sure if this works as expected https://github.com/tiangolo/typer/issues/450
