### ISSUE TITLE
How to not treat the version flag function as a command

### ISSUE THREAD

**Issue by wizard-28** [tiangolo/typer#372]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

import typer

app = typer.Typer()


def version_callback(value: bool):
    if value:
        print("Version")
        raise typer.Exit()


@app.command()
def cli(
    _: Optional[bool] = typer.Option(
        None, "-v", "--version", callback=version_callback, is_eager=True
    )
):
    ...


@app.command()
def other_command():
    ...


def main():
    app()


if __name__ == "__main__":
    main()
```

### Description

This generates the program as follows:
```console
Usage: test.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.

Commands:
  cli
  other-command
```

But I don't want the `cli` function to be treated as a command, I want to attach it's version argument to the main program.

### Operating System

Linux

### Typer Version

0.4.0

### Python Version

Python 3.8.10

### Additional Context

I need to have the `main()` function as that's the entry point to my program for poetry.

**Comment by shustinm** [comment]
This functionality is already implemented. You're looking for the [Callback](https://typer.tiangolo.com/tutorial/commands/callback/) decorator.

If you replace `typer.command` with `typer.callback` you'll get exactly what you wanted.
That's the only thing I modified in your code:
```python
from typing import Optional

import typer

app = typer.Typer()


def version_callback(value: bool):
    if value:
        print("Version")
        raise typer.Exit()


@app.callback()
def cli(
        _: Optional[bool] = typer.Option(
            None, "-v", "--version", callback=version_callback, is_eager=True
        )
):
    ...


@app.command()
def other_command():
    ...


def main():
    app()


if __name__ == "__main__":
    main()
```

And here's the output that was generated:
```
Usage: scratch_8.py [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --version
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or
                        customize the installation.

  --help                Show this message and exit.

Commands:
  other-command
```

Since you're now using  callback, you don't have to include the version parameter in every command, so I'd put it together with the callback function:
```python
from typing import Optional

import typer

app = typer.Typer()


@app.callback(invoke_without_command=True)
def cli(version: Optional[bool] = typer.Option(None, "-v", "--version", is_eager=True)):
    if version:
        print("Version")
        raise typer.Exit()


@app.command()
def other_command():
    ...


def main():
    app()


if __name__ == "__main__":
    main()
```
This produces the same `--help` output and is a bit cleaner in my opinion.

**Comment by wizard-28** [comment]
Works. Thank you!

**Comment by rafalkrupinski** [comment]
This solution disables help when no command is provided

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

Thanks for reporting back and closing the issue @wizard-28  👍

@rafalkrupinski if you are having problems, please create a new issue following the template.
