### ISSUE TITLE
Commands dont display when using --help unless you have two or more commands

### ISSUE THREAD

**Issue by travisrecupero** [tiangolo/typer#374]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer 

@app.command()
def version(name: str):
     typer.echo(f"Hello {name}")

#@app.command()
# def version2(name: str):
#      typer.echo(f"Hello {name}")

if __name__ == '__main__':
    app()
```

### Description

With version2 commented:
```
$ python bumpCversion.py --help
Usage: bumpCversion.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.
```
With verison2 uncommented:
```
$ python bumpCversion.py --help
Usage: bumpCversion.py [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.

Commands:
  version
  version2
```

### Operating System

Windows

### Typer Version

0.4.0

### Python Version

3.9.7

**Comment by archiif** [comment]
https://typer.tiangolo.com/tutorial/commands/one-or-multiple/#one-command-and-one-callback

**Comment by travisrecupero** [comment]
I noticed that and I feel this shouldn't be a _callback_. It would be more intuitive for the user to just add a single command. Nevertheless, solves the problem.
