### ISSUE TITLE
Typer don't work on Ubuntu 22.04

### ISSUE THREAD

**Issue by ghost** [tiangolo/typer#388]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
#!/bin/bash

your-awesome-typer-cli --install-completion bash|fish|zsh
```

### Description

Since upgrading to latest Ubuntu 22.04 auto-completion looks like to not work anymore. Even after removing previously created files by Typer and re-launching the command "--install-completion", it still does not work.

### Operating System

Linux

### Operating System Details

Ubuntu 22.04 LTS

### Typer Version

0.4.1

### Python Version

3.10.4

**Comment by targhs** [comment]
I can confirm this issue.
