### ISSUE TITLE
Is it possible to mix arguments/options with nested subcommands?

### ISSUE THREAD

**Issue by lbssousa** [tiangolo/typer#399]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

Given a Typer app with a subcommand `do-command` like this:
```
python myapp.py do-command ARGUMENT --option OPTION
```
and a CSV file like this:
```
HEADER-ARGUMENT,HEADER-OPTION
Argument 1,Option 1
Argument 2,Option 2
```
I would like to provide a subcommand `batch-csv` which makes my app iterate over a CSV file and run `do-command` for each line in the CSV file, filling `ARGUMENT` and `OPTION` with CSV values. A possible syntax would be this one:
```
python myapp.py batch-csv path/to/file.csv do-command ~HEADER-ARGUMENT --option ~HEADER-OPTION
```
which will be equivalent to this sequence of executions:
```
python myapp.py do-command Argument-1 --option Option-1
python myapp.py do-command Argument-2 --option Option-2
```

### Description

Does Typer currently support mixing arguments/options with nested subcommands, like in this example?
```
python myapp.py batch-csv path/to/file.csv do-command ~HEADER-ARGUMENT --option ~HEADER-OPTION
```

### Operating System

Linux, Windows

### Typer Version

0.4.1

### Python Version

3.10.4

### Additional Context

What I want to implement in my project is very similar to a feature already present in GAM:
https://github.com/GAM-team/GAM/wiki/BulkOperations

**Comment by lbssousa** [comment]
Responding to myself: I was able to achive the desired results with a callback:

```python
class State(TypedDict):
    batch_mode: bool
    batch_data: list[dict[str, str]]


_state: State = {"batch_mode": False, "batch_data": []}


def _make_arg(arg: str | None, row: dict[str, str]) -> str | None:
    if arg is None:
        return

    if isinstance(arg, bool):
        return arg

    pattern = re.compile(r"{{(.+?)}}")
    match = pattern.match(arg)

    if match is not None:
        header = match.group(1)

        return pattern.sub(row[header], arg) if header in row else None

    return arg


@app.callback()
def batch_callback(
    batch_file: Optional[str] = Option(
        None,
        help=(
            "CSV file for batch commands. If given, one can perform CSV header"
            " substitution in any CLI parameter by surrounding it with"
            " {{ and }}."
        ),
    ),
):
    if batch_file is not None:
        _state["batch_mode"] = True

        with open(batch_file, newline="") as csv_file:
            reader = DictReader(csv_file)
            _state["batch_data"] = [row for row in reader]
```

Then I can make my command work with a syntax similar to this one (with the help of `_make_arg()` function):
```
python myapp.py --batch-file path/to/file.csv do-command {{HEADER-ARGUMENT}} --option {{HEADER-OPTION}}
```

**Comment by tiangolo** [comment]
Thanks for coming back to close the issue and share your solution @lbssousa! 🍰 

> Sorry for the long delay! 🙈  I wanted to personally address each issue and they piled up through time, but now I'm checking each one in order.
