### ISSUE TITLE
[BUG] one command not detected, 2 commands ok

### ISSUE THREAD

**Issue by euri10** [tiangolo/typer#40]
### Describe the bug
using the below, we got 
```
Usage: main.py [OPTIONS] NAME
Try "main.py --help" for help.

Error: Missing argument "NAME".
```

while uncommenting cmd2 we got as expected
```
Usage: main.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  cmd1
  cmd2

```

```
import typer


app = typer.Typer()


@app.command()
def cmd1(name: str):
    typer.echo(f"Hello1 {name}")

# @app.command()
# def cmd2(name: str):
#     typer.echo(f"Hello2 {name}")

if __name__ == "__main__":
    app()
```

### Environment

* OS: [e.g. Linux]
* Typer Version [e.g. 0.3.0], get it with: 0.0.8

```bash
python -c "import typer; print(typer.__version__)"
```

* Python version, get it with: 3.8.1

```bash
python --version
```

**Comment by sander76** [comment]
When you comment 'cmd2’, 'cmd1' becomes the default and gets called when the script is executed even when not specified. This cmd wants the NAME argument, so hence the error.

**Comment by euri10** [comment]
well thanks @sander76 seems like I've been confused !

**Comment by tiangolo** [comment]
Thanks for the help here @sander76 ! :cake: :bowing_man: 

Thanks @euri10 for reporting back and closing the issue :+1:

**Comment by nnmer** [comment]
here is an explanation how to group a single command 
https://github.com/fastapi/typer/discussions/937#discussioncomment-10376326
