### ISSUE TITLE
[QUESTION] eagerness to mimic click.option ?

### ISSUE THREAD

**Issue by euri10** [tiangolo/typer#41]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

how can I mimic the following
```
@click.option(
    "--version",
    is_flag=True,
    callback=print_version,
    expose_value=False,
    is_eager=True,
    help="Display version and exit.",
)
```
added to a command it shortcuts the command to run the callback (described here: https://click.palletsprojects.com/en/7.x/options/#callbacks-and-eager-options)

I tried the following yet the callback is called no matter a command is or is not entered, even -`-help` is shortcut so I may be using the typer.Option wrongly or the is_eager kwarg is not used, no idea :)

click version:
```
def print_version(ctx, param, value):
    if not value or ctx.resilient_parsing:
        return
    click.echo('Version 1.0')
    ctx.exit()

@click.command()
@click.option('--version', is_flag=True, callback=print_version,
              expose_value=False, is_eager=True)
def hello():
    click.echo('Hello World!')
```
```
$ hello
Hello World!
$ hello --version
Version 1.0
```

typer version
```
import typer

app = typer.Typer()


def print_version(ctx, param, value):
    if not value or ctx.resilient_parsing:
        return
    typer.echo('Version 1.0')
    ctx.exit()


@app.command()
def hello(version: str = typer.Option('--version', is_flag=True, callback=print_version, expose_value=False, is_eager=True)):
    typer.echo('Hello World!')


if __name__ == '__main__':
    app()
```
```
$ python version.py
Version 1.0
$ python version.py --version
Error: --version option requires an argument
$ python version.py version
Version 1.0
```

**Comment by JnyJny** [comment]
I got your code fragment to work if I declared `version` like this:

```
import typer

app = typer.Typer()

def print_version(ctx, param, value):
    if not value:
        return
    typer.echo("Version MM.mm.pp")
    raise typer.Exit()

@app.command()
def main(version: bool = typer.option(False, "--version", "-v", is_eager=True, callback=print_version):
    print("foobar")
```

To be honest, I was hoping that Typer() would pass through the `click.version_option(VERSION)` decorator. This works but feels awkward.

**Comment by euri10** [comment]
> To be honest, I was hoping that Typer() would pass through the `click.version_option(VERSION)` decorator. This works but feels awkward.

yep that's the 1st thing I tried but so far didn't manage it
this solution works indeed but you need to type `app main --version` while on click `app --version` would make it, 
there might be a way !

**Comment by tiangolo** [comment]
Thanks for the discussion @euri10  and @JnyJny !

I just added docs about `--version` with `is_eager`: https://typer.tiangolo.com/tutorial/options/version/

**Comment by euri10** [comment]
thanks

**Comment by randallpittman** [comment]
Hi, Is there a way to have a `--version`-type eager option with required Arguments? That is, the arguments are required unless you're just calling `--version`.

**Comment by tiangolo** [comment]
@randallpittman probably better to ask in a new issue following the template. 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
