### ISSUE TITLE
[QUESTION] How to implement global options.

### ISSUE THREAD

**Issue by shmokmt** [tiangolo/typer#42]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [ ] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I implement global options like `--install-completion`, `--show-completion`?

Click allows to easily implement global options in context.
I want a simple function similar to typer.

### Additional context

I often implement global options such as `--env` and` --debug`.

**Comment by thedrow** [comment]
By inspecting the code it seems like this is not possible right now.
How do we imagine such API?

**Comment by euri10** [comment]
> By inspecting the code it seems like this is not possible right now.
> How do we imagine such API?

I'd be tempted to say like in click with a `group` decorator, so as to stay in familiar territory :)

I tried various stuff with the add_typer command without being able to achieve the desired result.
That would be awesome to get an answer.

This is the main blocker identified for us so far switching from click as we make quite a fair use of global switches, most often for logging

**Comment by dedsm** [comment]
I imagine this as an option in the `app` ie Typer instances, that way it'd work even without subcommands

**Comment by tiangolo** [comment]
Thanks for the discussion here everyone!

Here are the new docs for using `is_eager`: https://typer.tiangolo.com/tutorial/options/version/ :tada: 

And here for adding global *CLI options*: https://typer.tiangolo.com/tutorial/commands/callback/ :rocket:

**Comment by shmokmt** [comment]
Thank you so much 😄

**Comment by jstafford5380** [comment]
This doesn't seem to even work. Even the example that's linked shows an error `Error: no such option --verbose`. This has been my experience as well

![image](https://github.com/tiangolo/typer/assets/47302800/c826ee36-0012-4d4c-b775-85beac541c2f)
