### ISSUE TITLE
Examples in README.md are malformed on GitHub

### ISSUE THREAD

**Issue by Andrew-Sheridan** [tiangolo/typer#432]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
n/a
```

### Description

The text snippets that are displayed in the markdown files on github are malformed.

For example in the [Run It](https://github.com/tiangolo/typer#run-it) section this is the content as displayed:

Or as an image:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/50179676/180009626-80c8e5af-060e-4cde-9d72-9e665b19dec2.png">
It shouldnt have all the 'noise'

It should look closer to this:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/50179676/180008577-15e63edd-1443-4dce-9e93-69a024bcc4ad.png">

We may need to modify `build-docs.sh` to account for the pretty `rich` formatting. Perhaps somebody skilled with bash / sed / regex could modify this line: 
https://github.com/tiangolo/typer/blob/83bf2fc99d948d400dba2cc88193c863c922fad2/scripts/build-docs.sh#L5

?

### Operating System

Other

### Typer Version

0.6.1

### Python Version

3.10.0

**Comment by lahwran** [comment]
bump!

**Comment by tiangolo** [comment]
Thanks! I just fixed this. :nerd_face:
