### ISSUE TITLE
[BUG] Replace `__main__.py` to `python3 -m something` in help messages

### ISSUE THREAD

**Issue by lorddaedra** [tiangolo/typer#44]
### Describe the bug

Not a big bug but just good to change help message. 

`__main__.py` --> `python3 -m something`

### To Reproduce

Create `__main__.py`, put some code there. Try to execute it via `python3 -m`:
```
$ python3 -m something
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...
```

**Comment by lorddaedra** [comment]
Expected:
```
$ python3 -m something
Usage: python3 -m something [OPTIONS] COMMAND [ARGS]...
```

**Comment by humrochagf** [comment]
Adding more info to that, even if you set typer name it does not change:

```python
app = typer.Typer(name='something')
```

By inspecting the `app.info.name` the value is set, but it seems that is not being used.

**Comment by tiangolo** [comment]
Thanks for the discussion here!

The best way to do it is to create a Python package, here's a new guide for that: https://typer.tiangolo.com/tutorial/package/

Also, if you just want to run small scripts, you can use the new **Typer CLI**: https://typer.tiangolo.com/typer-cli/ :rocket:
