### ISSUE TITLE
[QUESTION] How to gradually migrate from Click?

### ISSUE THREAD

**Issue by thedrow** [tiangolo/typer#45]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

I have a CLI application written using Click and I'd like to migrate to Typer.
It seems like there's no way to gradually migrate from Click to Typer and that's a refactor I'd like to avoid doing all at once.
We already did the refactor to migrate to Click and I'd like to avoid another large refactor.

Is there a way to call `typer.run()` on a regular Click group and migrate each command once at a time?

### Additional context

The code can be found [here](https://github.com/celery/celery/pull/5718).

**Comment by tiangolo** [comment]
Hey @thedrow ! That's very cool! I would be very proud if Celery used Typer :blush: :rocket: 

I just added docs for exactly this use case: https://typer.tiangolo.com/tutorial/using-click/

**Comment by thedrow** [comment]
Thanks!
