### ISSUE TITLE
Enum Option default is `None` [BUG]

### ISSUE THREAD

**Issue by sullivancolin** [tiangolo/typer#46]
### Describe the bug

If an enum option type is not given, it's value is `None` instead of the specified default value.  If the option is specified then it works as expected

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

* Create a file `main.py` with:

```Python
from enum import Enum

import typer


class NeuralNetwork(str, Enum):
    simple = "simple"
    conv = "conv"
    lstm = "lstm"


def main(
    network: NeuralNetwork = typer.Option(NeuralNetwork.simple, case_sensitive=False)
):
    typer.echo(f"Training neural network of type: {network.value}")


if __name__ == "__main__":
    typer.run(main)

```

* Call it with:

```bash
python main.py
```

* It outputs:

```
Traceback (most recent call last):
...
  File "tutorial002.py", line 15, in main
    typer.echo(f"Training neural network of type: {network.value}")
AttributeError: 'NoneType' object has no attribute 'value'
```

* But I expected it to output:

```
Training neural network of type: simple
```

### Expected behavior
I would expect that the specified default value of an enum would be passed to the function parameter instead of `None` when the option is not provided.

### Environment

* OS: [macOS]
* Typer Version [0.0.8]
* Python version [3.7.6]

**Comment by JnyJny** [comment]
As a workaround, I was able to get the expected behavior by substituting:

```python
def main(
    network: NeuralNetwork = typer.Option(NeuralNetwork.simple.value, case_sensitive=False)
):
```

**Comment by tiangolo** [comment]
Hi @sullivancolin , thanks for the report! And thanks for the idea @JnyJny .

I wasn't able to reproduce it with the latest, so I think the underlying bug might have been fixed by Click 7.1, released recently.

Could you confirm?

**Comment by sullivancolin** [comment]
Yup. I can confirm new release of Click fixed the issue! 🎉   I'll close the issue and the PR

**Comment by tiangolo** [comment]
Great! Thanks for reporting back and closing it :+1:
