### ISSUE TITLE
Support click-help-colors [FEATURE]

### ISSUE THREAD

**Issue by sullivancolin** [tiangolo/typer#47]
### Problem
I want to be able to replicate the functionality of [click-contrib/click-help-colors](https://github.com/click-contrib/click-help-colors) to add colors to help text for easier readability

### Ideal API

```python
import typer
from click_help_colors import HelpColorsGroup

app = typer.Typer(cls=HelpColorsGroup,
    help_headers_color='yellow',
    help_options_color='green')
```

### Attempted
By subclassing `HelpColorsGroup` and explicitly setting the colors in the `__init__` it is possible to get colors 

```python
import typer
from click_help_colors import HelpColorsGroup


class CustomHelpColorsGroup(HelpColorsGroup):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.help_headers_color = "blue"
        self.help_options_color = "yellow"


app = typer.Typer(cls=CustomHelpColorsGroup)


@app.command()
def test_function(
    name: str = typer.Option("World", "--name", "-n", help="name to say hello")
) -> None:
    typer.echo(f"Hello {name}!")


@app.command()
def other() -> None:
    typer.echo("other")


if __name__ == "__main__":
    app()
```
![typer_help_colors](https://user-images.githubusercontent.com/10760217/73690054-8ac1fc00-469d-11ea-911a-4163f82ba46a.png)

However the color does not propagate to sub command help text

![sub_command_no_color](https://user-images.githubusercontent.com/10760217/73690168-c65cc600-469d-11ea-9018-5b2c8bfcd277.png)

**Comment by tiangolo** [comment]
You have to also provide the Command class, like:

```Python
import typer
from click_help_colors import HelpColorsGroup, HelpColorsCommand


class CustomHelpColorsGroup(HelpColorsGroup):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.help_headers_color = "blue"
        self.help_options_color = "yellow"


class CustomHelpColorsCommand(HelpColorsCommand):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.help_headers_color = "blue"
        self.help_options_color = "yellow"


app = typer.Typer(cls=CustomHelpColorsGroup)


@app.command(cls=CustomHelpColorsCommand)
def test_function(
    name: str = typer.Option("World", "--name", "-n", help="name to say hello")
) -> None:
    typer.echo(f"Hello {name}!")


@app.command(cls=CustomHelpColorsCommand)
def other() -> None:
    typer.echo("other")


if __name__ == "__main__":
    app()
```

This is because `HelpColorsGroup` defines its own method `command` that overrides the default `command` method from Click, to provide its own `HelpColorsCommand` class instead of the default `Command` class.

But Typer doesn't modify nor use Click classes directly, when you use `@app.command()` that is not the same as with a Click `@cli.command()`.

Typer doesn't modify the function to replace it with an instance of a class, instead, it registers the function to use and the class to use, and then it creates the specific objects when you call it. But doing it as described above should work fine (I just tested it :smile: ).

**Comment by daddycocoaman** [comment]
Just wanted to add, if you want to avoid having to add the `cls` to every command and/or Typer, you can just subclass them. So adding onto @tiangolo, it would be something like this:

```python
class CustomTyper(typer.Typer):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, cls=CustomHelpColorsGroup, **kwargs)

    def command(self, *args, **kwargs) -> typer.Typer.command:
        return super().command(args, cls=CustomHelpColorsCommand, **kwargs)
```
Hope this helps.

**Comment by ssbarnea** [comment]
Here is a full example I found of using click-help-color with typer https://github.com/daddycocoaman/AzDummy/blob/78438183c95102c5aed5af3578af31601bd7f423/azdummy/core/typer.py#L2

**Comment by ssbarnea** [comment]
Apparently typer is no longer compatible with click-help-colors since 0.7
