### ISSUE TITLE
prompt adding additional characters to prompt output

### ISSUE THREAD

**Issue by rlthompson-godaddy** [tiangolo/typer#474]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer


app = typer.Typer(no_args_is_help=True)


@app.command(no_args_is_help=True)
def example(
    user: str = typer.Option("", envvar="EXAMPLE_USER", prompt="user", help="example user to print"),
    password: str = typer.Option("", envvar="EXAMPLE_PASSWORD", prompt="password", hide_input=True, help="example password to print")
    ):
    """Example command."""
    print(f"{user} | {password}")
```

### Description

* I am creating a simple cli command that has optional parameters that take in a user name and password
* When running the above command, I notice that the prompt is adding `[]` to the prompt string:
```python
user []:
password []:
```
* I have tried this without a custom prompt string, by setting prompt to true `prompt=True` but the issue occurs there too
* What I expect to occur is that `[]` would not be present in the prompt string output to CLI

### Operating System

Linux

### Operating System Details

Alma Linux 9

### Typer Version

0.6.1

### Python Version

Python 3.8.15

### Additional Context

The above example code is just that, an example. The actual command also has positional arguments and is itself a nested subcommand. Don't know if that impacts this.

**Comment by JeromeK13** [comment]
Hey

I've did not verify that one but Ive you really dont want these [] you could add a callback like this to format the value passed from the input.

```python

import typer


app = typer.Typer(no_args_is_help=True)

def some_callback(ctx, parameter, value):
    print(value)


@app.command(no_args_is_help=True)
def example(
    user: str = typer.Option("", envvar="EXAMPLE_USER", prompt="user", help="example user to print", callback=some_callback) ):
    """Example command."""
    print(f"{user} | {password}")
```

**Comment by tiangolo** [comment]
I think that is showing the default value, an empty string.

You could also try to prompt the user manually.

This comes directly from Click, so there's not really much that Typer can do about it. 😅
