### ISSUE TITLE
Use `issubclass` for all annotation checks

### ISSUE THREAD

**Issue by aguckenber-chwy** [tiangolo/typer#499]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer

import re

from pydantic import ConstrainedStr


class Uid(ConstrainedStr):
    regex = re.compile(r"^[A-Za-z0-9-_]+$")

app = typer.Typer()

@app.command()
def example(
    uid: Uid = typer.Argument()
):
    print("hello-world")
```

### Description

We are trying to use `constr` from the pydantic library as a CLI annotation but it fails with:

> RuntimeError: Type not yet supported: <class Uid>

I see the reason is because type has a list of set types it supports. The real issue is the
[`if annotation == str:`](https://github.com/tiangolo/typer/blob/master/typer/main.py#L692) in the checks.

### Wanted Solution

We could use pydantic types as well as remedy some of the other complains on annotations if all the primitive annotation checks used some variant of `issubclass` instead of a hard `==`. 

Doing a quick local test with swapping the following:

```python
if annotation == str:
```

```python
if lenient_issubclass(annotation, str):
```

Appears to work. Although some more tests will be needed on ordering since:
```python
class example(str, Enum):
```

May also catch that first `if`.

### Wanted Code

```python
import typer

import re

from pydantic import ConstrainedStr


class Uid(ConstrainedStr):
    regex = re.compile(r"^[A-Za-z0-9-_]+$")

app = typer.Typer()

@app.command()
def example(
    uid: Uid = typer.Argument()
):
    print("hello-world")


`example foo`: should work
`example foo@`: should fail
```

### Operating System

macOS

### Typer Version

0.6.1

### Python Version

3.10.4

**Comment by tiangolo** [comment]
Yep, but Pydantic is not used internally here, its types wouldn't do their validation, etc.

I have considered supporting Pydantic, but I can't make it a hard dependency, so it would have to be optional, which makes things much harder. Maybe in the future, but first I have a lot of features to handle.

**Comment by aguckenber-chwy** [comment]
Oho... I didn't notice that pydantic requires more under the hood to support it as a hard dependency, now testing it I see your point. One option is to do a light coupling like:
```python
try:
    import pydantic

    PYDANTIC_INSTALLED = True
except ModuleNotFoundError:
    PYDANTIC_INSTALLED = False
```
But that may be a code smell for you so I will just leave it as an idea.

I would LOVE to see pydantic support in the future, at least to the point of [constrained types](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types) since regex, min/max length, and other checks would be SUPER handy in a CLI. Main thing I was using it for was a regex pattern check. In truthfulness, being a CLI, Typer doesn't need full model checks, but adding the constrained types  from pydantic (even forking them) would be a great addition to the Typer suite.

We can work around it for now. Thank @tiangolo, still a great CLI tool.

**Comment by tiangolo** [comment]
Thanks! Yep, there are are lot of harder parts to handle down the line... So it will take a bit. 😅
