### ISSUE TITLE
generate markdown documentation

### ISSUE THREAD

**Issue by tmbdev** [tiangolo/typer#51]
### The solution you would like

```Bash
    $ mycommand --help-markdown-documentation > mycommand.md
```

It would be nice if there was an automatic way of generating a markdown documentation from the Typer help texts.

### Describe alternatives you've considered

A script like the following kind of works, but it's fragile and doesn't have access to all the same information as the Typer library.

```Bash
#!/bin/bash

for command in "$@"; do
    echo
    echo "# $command (command)"
    echo
    $command --help | sed '1,/^Commands:/d' | awk '{print $1}' |
    while read subcommand; do
        echo
        echo "## $command $subcommand (subcommand)"
        echo
        echo '```generic'
        obj $subcommand --help
        echo '```'
        echo
    done
done
```

**Comment by tiangolo** [comment]
You can now generate Markdown docs for a Typer app with the new Typer CLI: https://github.com/tiangolo/typer-cli#generate-docs

It's not documented yet in the main docs, but you can use it already.

**Comment by pavel-razgovorov** [comment]
Hello @tiangolo.

I tried to use the docs generator tool from the typer-cli and, for some reason, it is not working in my case. Here is my project's structure:

```
├── README.md
├── my_script
│   ├── __init__.py
│   ├── __main__.py
│   └── main.py
├── poetry.lock
├── pyproject.toml
└── tests
    ├── __init__.py
    └── test_my_script.py
```

By following your documentation [here](https://typer.tiangolo.com/typer-cli/#generate-docs), this is what I execute and what I am seeing:

```
typer my_script/main.py utils docs
Usage: typer [OPTIONS] [REPO_PATH]
Try 'typer --help' for help.

Error: Got unexpected extra arguments (utils docs)
```

It seems like typer directly launches my script (the `REPO_PATH` argument comes from it) and ignores the rest of the commands (utils and docs). Is this a bug or am I doing something wrong?
