### ISSUE TITLE
Long help text wraps too narrowly

### ISSUE THREAD

**Issue by miohtama** [tiangolo/typer#511]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
@app.command()
def start(

    # Strategy assets
    id: str = typer.Option(None, envvar="id help="Here we have a very long long long help text that wraps")
)
```

### Description

The long help text does not respect the terminal width and wraps too early.

Here is an example screenshot of Ubuntu Linux terminal where you can see the Typer help text do not utilize the full terminal width, making the options harder to read.

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/49922/204050095-dd43144e-7b63-414c-88a1-e2101219a692.png">

I assume this is an underlying `click` issue, but I am filing the issue here, as I am a Typer user and I could not help regarding this issue in Github, Google or StackOverflow.

For a comparison, here is a screenshot of Go console program and it seems to be able to the wrapping fine:

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/49922/204050236-2246f048-448b-479d-9489-96feda0a1238.png">

### Operating System

Linux

### Operating System Details

Tested on

- Ubuntu Linux
- macOS

### Typer Version

0.4.2  

### Python Version

3.10

**Comment by meirdev** [comment]
This is how the width is calculated:

https://github.com/pallets/click/blob/c65c6ad18471448c0fcc59ef53088787288c02cc/src/click/formatting.py#L122-L131

So the best option is to provide `max_width`:

```python
app = typer.Typer(context_settings={
    "max_content_width": 120,
})
```

**Comment by miohtama** [comment]
Is there an option to make this depend on the terminal width, like other UNIX software seems to be doing?

**Comment by meirdev** [comment]
Yes, but if you set the max width big enough it's the same.

```python
import shutil
...
"max_content_width": shutil.get_terminal_size().columns
...
```

**Comment by miohtama** [comment]
Thank you @meirdev - works like a charm!

**Comment by taranlu-houzz** [comment]
@meirdev I'm not having luck with the solution you suggested. I have a subcommand and also use a callback for top-level common options. Setting `context_settings` at the `typer.Typer()` level does not seems to have any effect, and unlike what is described in #365, doing that on the subcommand also does not have an effect of either. Do you happen to know if this is a known limitation currently?

**Comment by bckohan** [comment]
It doesn't look like you were using rich, but if you are the Console used to generate helps does not respect the max_content_width context setting that click uses. It does respect the  TERMINAL_WIDTH environment variable.

Seems like any relevant click settings should probably make their way to the Console constructor.
