### ISSUE TITLE
[FEATURE] Typing Support (PEP 561)

### ISSUE THREAD

**Issue by dbanty** [tiangolo/typer#53]
### Is your feature request related to a problem

I would like mypy to be able to type check usages of Typer.  Currently running mypy on a project that uses Typer gives the "Cannot find implementation or library stub for module named 'typer'" error.

### The solution you would like

Because everything is type annotated in the code base, I believe this is as simple as adding a `py.typed` file to the distribution.

**Comment by tiangolo** [comment]
Thanks! Good point. This should have been solved by #58 .

Just released as version `0.0.9`.
