### ISSUE TITLE
Documentation is misleading. new `typer.run` behavior

### ISSUE THREAD

**Issue by voronind** [tiangolo/typer#531]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer


def main():
    print("Hello World")


if __name__ == "__main__":
    typer.run(main)
```

### Description

This page of documentation is not actual - https://typer.tiangolo.com/tutorial/first-steps/
`typer.run` don't add completion options since 0.7 version but animation has version 0.6 behavior

### Operating System

Linux, Windows, macOS, Other

### Typer Version

0.7

### Python Version

any

**Comment by tiangolo** [comment]
Thanks! I just fixed it. :nerd_face:
