### ISSUE TITLE
See if rich 13.x is compatible

### ISSUE THREAD

**Issue by whardier** [tiangolo/typer#532]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# No code
```

### Description

Rich 13.x has been released and typer is now holding back this library.. however the release alters the minimum python version to 3.7.  This issue is being brought up for information purposes.

### Operating System

Linux

### Operating System Details

Any OS

### Typer Version

HEAD

### Python Version

3.9.14

**Comment by kkirsche** [comment]
Fixed in https://github.com/tiangolo/typer/pull/524

**Comment by musicinmybrain** [comment]
Fixed in 8.0.0.

**Comment by tiangolo** [comment]
Yep, this should be fixed in 0.8.0 :rocket: :tada:
