### ISSUE TITLE
can't get --install-completion to work

### ISSUE THREAD

**Issue by zzztimbo** [tiangolo/typer#54]
given this program:

```
#!/usr/bin/env python
  port typer

app = typer.Typer()

@app.command()
def foo():
    print('foo')

@app.command()
def bar():
    print('bar')

if __name__ == "__main__":
    app()
```

I run: `./foo.py --install-completion`

I see: 
```
zsh completion installed in /Users/tchan/.zshrc.
Completion will take effect once you restart the terminal.
```

I source my `.zshrc` and then type `./foo.py` and hit tab

I see this: 

```./foo.py env: foo.py: No such file or directory```

**Comment by DarkaMaul** [comment]
Actually, there is a bug with the generation because the full path of the app file (foo in your case) is not written.

Temp workaround:
Replace the generated line (in `~/.zshrc`) by the following one:
```bash
eval $(env COMMANDLINE="${words[1,$CURRENT]}" _APP.PY_COMPLETE=complete-zsh python PATH_TO_FOO/foo.py)
```

You could also report the bug to [Click-Completion](https://github.com/click-contrib/click-completion/issues )

**Comment by tiangolo** [comment]
Hi everyone! Thanks for the discussion here.

For auto completion to work, you have to create a Python package, there's a new section in the docs about that: https://typer.tiangolo.com/tutorial/package/ :memo: 

If you just want to run simple scripts and have completion in your shell, you can use the new **Typer CLI**: https://typer.tiangolo.com/typer-cli/ :rocket: :keyboard:

**Comment by ShivKJ** [comment]
I am still facing the same issue. Let me know if this has been resolved

**Comment by shelper** [comment]
same here, i have a tool called zetta, that i made it a command line tool with `[tool.poetry.scripts]`
I run `poetry install`, and then `which zetta`, shows me where the zetta executable is 
then i run `zetta --install-completion zsh`, and got message confirmed and in my `~/.zfunc/_zetta` i have 
```
_zetta_completion() {
eval $(env COMMANDLINE="${words[1,$CURRENT]}" _APP.PY_COMPLETE=complete-zsh zetta)
}
```
but the autocompletion still does not work....

same steps for bash works...

**Comment by shelper** [comment]
well , i think i solved this problem by adding the following lines to my .zshrc
hope this helps
```
autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc
compinit
```

**Comment by paw-lu** [comment]
I'm _still_ not able to get completion to work.

My setup is pretty much identical to @shelper

My (entire) `~./zshrc`:

```zsh
# ~/.zshrc
autoload -Uz compinit
fpath+=~/.zfunc
compinit
```

My `~/.zfunc/_nbpreview`:

```zsh
#compdef nbpreview

_nbpreview_completion() {
  eval $(env _TYPER_COMPLETE_ARGS="${words[1,$CURRENT]}" _NBPREVIEW_COMPLETE=complete_zsh nbpreview)
}

compdef _nbpreview_completion nbpreview
```

Seems the correct file is registered,
but when it comes to actual completion,
nothing happens.


```sh
# Command to show which completion file is registered
% whence -v $_comps[nbpreview]
_nbpreview_completion is a shell function from /Users/pawlu/.zfunc/_nbpreview

% nbpreview --<TAB>
# No output, completion
```

**Comment by wpm** [comment]
From [here](https://lightrun.com/answers/tiangolo-typer-bug-typer-cli-and-packages-not-auto-completing-) I got the workaround to add `compinit -D` to the end of my `.zshrc` file. I have no idea what it means, but it worked.

**Comment by svlandeg** [comment]
Related PR to fix autocompletion with the `zsh` shell, similar to the fix @shelper mentioned: https://github.com/tiangolo/typer/pull/237
