### ISSUE TITLE
[FEATURE] callback should not be called on --help for a subcommand

### ISSUE THREAD

**Issue by samuelcolvin** [tiangolo/typer#55]
Again, thanks for the great library. So far it's be great to use (though some of the more advanced features I think lack some documentation).

```py
from pathlib import Path
import typer
app = typer.Typer()

@app.command()
def bar(y: str):
    print('y =', y)

@app.callback()
def my_callback(path: Path = 'testing'):
    """
    testing
    """
    print('calling my_callback...')
    assert path.exists(), path

if __name__ == '__main__':
    app()
```

If I execute `python test.py` or `python test.py --help` then correctly `my_callback` is not called.

But if I execute `python test.py bar --help` then `my_callback` is called. I think in this case `my_callback` should not be called.

If it is called, is there a clean way to check if it's being called as part of a help command other than `if '--help' in sys.argv: return`?

**Comment by tiangolo** [comment]
Hey @samuelcolvin !

I'm glad (and flattered) that you like it ( [clearly Pydantic inspired a lot of the ideas](https://typer.tiangolo.com/alternatives/#pydantic) ) :nerd_face: .

You can achieve it with a combination of:

A *CLI Option* callback: https://typer.tiangolo.com/tutorial/options/callback-and-context/

Using `is_eager`, as with `--version`: https://typer.tiangolo.com/tutorial/options/version/

And using the `Context` to make sure the main Typer callback is not executed if there's a sub command: https://typer.tiangolo.com/tutorial/commands/context/#exclusive-executable-callback

Those are all new docs :rocket:
