### ISSUE TITLE
SIGINT from docker is ignored

### ISSUE THREAD

**Issue by fakuivan** [tiangolo/typer#624]
Read the title. These templates for issues are worse than most eulas.

My cli applications written with typer don't handle sigints sent by docker.

**Comment by jonaslb** [comment]
Can't reproduce, here it seems sigint causes a typer-based script to close just fine. You're probably not running it right in docker, or you have something else intercepting the signals. 

Notably if you use `COMMAND` with certain images, they are not `exec`'d like you might expect, but there's some shell that wraps it and doesn't pass on the signals properly. To avoid it, always prefer the array version of `ENTRYPOINT`, and if you have some init script wrapper, remember to `exec python3 (....)` when you start your application at the end of it.

**Comment by fakuivan** [comment]
I'm using `entrypoint` myself and pointing it to the python script with the appropriate shebang, unless the official python containers from docker are doing something really weird then I don't think this is an environment issue

https://github.com/fakuivan/docker-syncthing-system/blob/13efffdfe168260669e1fa3dc6eafc67066708ce/Dockerfile

**Comment by jonaslb** [comment]
Ok, I can see that you have a 466 line script with a ton of libraries and some threading stuff, too. Usually when submitting a bug to an upstream project, it's a good idea to have a minimal piece of code that demonstrates the issue very clearly. What you have is a "haystack" where you are claiming the "needle" is typer, but I don't really think that's true, or at least it is not demonstrated here in any way.

**Comment by fakuivan** [comment]
I've had this happen in other private repos where I also use typer, and I know that typer has some handling code for sigint, so I thought I could get some help here. I've tried to isolate to isolate the issue and it seems to be related with docker compose. Even this times out at 10s when running `docker compose down`:

```yaml
services:
  alpine-sh:
    image: alpine
    entrypoint: [ "sh", "-c", "while true; do sleep 10; done;" ]
```

Thanks for the help. I'm closing this, as it doesn't seem to be related.
