### ISSUE TITLE
[BUG] List values get split by character when prompted

### ISSUE THREAD

**Issue by StephenBrown2** [tiangolo/typer#74]
### Describe the bug

When an option's type is `List[str]`, the input gets split by character, as it would if I just called `list("string")`

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

* Create a file `main.py` with:

```Python
import typer

from typing import List

app = typer.Typer()


@app.command()
def main(
    prefix: List[str] = typer.Option(
        ...,
        "-p",
        "--prefix",
        help="Prefix to filter, can specify multiple times",
        prompt="Prefix",
    )
):
    typer.echo(f"{prefix=}")


if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python main.py
```

* It outputs:

```
Prefix [()]: abcd qwerty
prefix=('a', 'b', 'c', 'd', ' ', 'q', 'w', 'e', 'r', 't', 'y')
```

* But I expected it to output:

```
Prefix [()]: abcd qwerty
prefix=('abcd', 'qwerty')
```

or

```
prefix=('abcd qwerty')
```

* When using multiple flags, it is correct:

```
python migrate_dcos/test_strings.py -p abcd -p qwerty
prefix=('abcd', 'qwerty')
```

### Expected behavior

I expected the values to be automatically (or with an `Option` argument) split on spaces, rather than the single string getting cast to a tuple.

### Environment

* OS: macOS
* Typer Version: 0.1.0
* Python version: Python 3.8.1

### Additional context

I can work around it for space and comma-delimited values with:

```Python
def fix_strlist_value(value):
    if " " in value or "," in value or all(len(i) == 1 for i in value):
        return [k for k in "".join(value).replace(",", " ").split(" ") if k]
    return value
```

but I'd rather not have to.

**Comment by tiangolo** [comment]
This is actually a bug/feature request for Click, not really for Typer.

Here's the equivalent Click app showing the same behavior:

```Python
import click

@click.command()
@click.option("-p", "--prefix", help="Prefix to filter, can specify multiple times", prompt="Prefix", multiple=True)
def main(prefix):
    click.echo(f"{prefix}")


if __name__ == "__main__":
    main()
```

You might want to create an issue in the main Click repo.

But I suspect that prompting for a multi-value option is probably not supported. :disappointed:

**Comment by StephenBrown2** [comment]
Good to know it's an upstream thing!

> But I suspect that prompting for a multi-value option is probably not supported. 😞

Yeah, it may or may not make sense, so I'll probably just stick with my "fix".

**Comment by tiangolo** [comment]
Cool, thanks for reporting back!

May we close this issue then?

**Comment by StephenBrown2** [comment]
Yup, sorry, thought that would have happened already.
