### ISSUE TITLE
`typer run` with a script declaring multiple functions

### ISSUE THREAD

**Issue by weakish** [tiangolo/typer#79]
When there are more than one function declared in a Python script,
and none of them is named `main`,
it seems that typer will randomly choose the function to run when using `typer that-script.py run ARG`.

For example:

```python
def hello(name: str):
    print(f"Hello {name}!")

def plus_one(n: int):
    print(n + 1)
```

Several runs:

```sh
$ typer hello.py run "world"
Usage: typer run [OPTIONS] N
Try 'typer run --help' for help.

Error: Invalid value for 'N': world is not a valid integer
$ typer hello.py run "typer"
Hello typer!
$ typer hello.py run 1
2
$ typer hello.py run 0
Hello 0!
```

I suggest the following alternatives to the current undefined behavior:

0. Reports an error and abort, telling the developer that they must declare only one function in the script, or declare multiple functions with one of them named `main`
1. (I think this will be cool but maybe over-engineered) Try to dispatch based on guessing the type of command line argument. For the example above, first try to convert the argument to an integer. If succeed, invoke the function with matching signature (`plus_one`), otherwise invoke `hello`. If there are more than one functions matched, or if none of the functions matched, report an error instead.

**Comment by tiangolo** [comment]
That's interesting behavior.

So, all the defaults are explained here: https://typer.tiangolo.com/typer-cli/#defaults

For functions, it's `main`, `cli`, `app`. In that order.

When none of the defaults are available, Typer CLI will use the first function found when importing the module. I was expecting Python to import them in order of declaration :thinking: 

But anyway, the best way to solve it is probably to declare explicitly which function to use: https://typer.tiangolo.com/typer-cli/#options
