### ISSUE TITLE
[QUESTION] Dependency Injection

### ISSUE THREAD

**Issue by Leletir** [tiangolo/typer#80]
### First check

* [X] I used the GitHub search to find a similar issue and didn't find it.
* [X] I searched the Typer documentation, with the integrated search.
* [X] I already searched in Google "How to X in Typer" and didn't find any information.
* [X] I already searched in Google "How to X in Click" and didn't find any information.

First of all, thank you for your amazing tools, it helps my team and I to build great products !

### Description

How can I inject a Database connection to a "cli function" ? 

I was looking for a mecanism like `Depends` in FastAPI (https://fastapi.tiangolo.com/tutorial/dependencies/)

### Additional context

I'm trying to create a cli which read files and insert them to a database but one of my subcommands is depending of a Database connection.

For the moment I've used:

```
save_app = typer.Typer()


def get_db():
    typer.echo("Initializing database")
    db = VerticaDB(
        host=conf.get_vertica_host(),
        port=conf.get_vertica_port(),
        user=conf.get_vertica_user(),
        password=conf.get_vertica_password(),
        database=conf.get_vertica_database()
    )
    return db


@save_app.command("save")
def ingest_snitch_file(
        path_to_log_file: Path = typer.Option(
            ...,
            exists=True,
            readable=True,
            envvar='PATH_TO_SNITCH_FILE'
        ),
        db=typer.Option(
            hidden=True,
            default=get_db()
        )
):
    """
    Ingest snitch files to Database
    """
    snitch = Snitch(
        db=db,
        path_to_snitch=path_to_log_file,
        table_schema=conf.get_vertica_table_schema(),
        table_name=conf.get_vertica_table_name()
    )
    snitch.insert_log_to_database()
```

**Comment by tiangolo** [comment]
Hey @Leletir ! I'm glad the tools are being useful! :tada: 

In this use case, what would be the advantage of having the DB session provided by a dependency injection system?

In other words, what would be wrong with something explicit? Creating the DB in the function with:

```Python
db = get_db()
```

like in:

```Python
save_app = typer.Typer()


def get_db():
    typer.echo("Initializing database")
    db = VerticaDB(
        host=conf.get_vertica_host(),
        port=conf.get_vertica_port(),
        user=conf.get_vertica_user(),
        password=conf.get_vertica_password(),
        database=conf.get_vertica_database()
    )
    return db


@save_app.command("save")
def ingest_snitch_file(
        path_to_log_file: Path = typer.Option(
            ...,
            exists=True,
            readable=True,
            envvar='PATH_TO_SNITCH_FILE'
        )
):
    """
    Ingest snitch files to Database
    """
    db = get_db()
    snitch = Snitch(
        db=db,
        path_to_snitch=path_to_log_file,
        table_schema=conf.get_vertica_table_schema(),
        table_name=conf.get_vertica_table_name()
    )
    snitch.insert_log_to_database()
```

**Comment by Leletir** [comment]
Hello @tiangolo,

The developer experience is just 👌

You're right, in this case it's not very usefull as we can provide the dependency easily. I was the just wondering if it's possible ?

**Comment by larsrinn** [comment]
I'm interested in a similar use case, as I'm trying to write a CLI to communicate with another server. The commands require the server address, user name, password, etc. in order to establish the connection.

It would be great, if it was possible to establish the connection (and handle the errors, etc.) in one function and inject the result of this into the single commands, in order to avoid the duplication of the options. 

Similar like this:

```python
import typer

app = typer.Typer()


def client(
    host: str = typer.Option(...),
    username: str = typer.Option(...),
    tls: bool = True,
    password: str = typer.Option(..., prompt=True, hide_input=True),

) -> Client:
    client = Client(host)
    if not client.connect(
            username, password, starttls=tls
    ):
        raise typer.Exit(code=1)
    return client


@app.command()
def command1(
    client: Client = typer.Dependency(client)
):
    assert client.is_connected


@app.command()
def command2(
    client: Client = typer.Dependency(client)
):
    pass


if __name__ == "__main__":
    app()
```

So `typer` would have to resolve the arguments and options for the dependency, execute that method and pass the value into the command being called. I didn't think this through any further than that, so I don't know what the implications would be.

I'm sure this would also be possible by using meta programming or some fancy decorator that modifies the function signature. But I'd rather not get my hands that dirty.

**Comment by tiangolo** [comment]
Thanks for the report @Leletir !

@larsrinn I think you could achieve something very similar by adding those settings to a callback: https://typer.tiangolo.com/tutorial/commands/callback/

That are then shared by each command, probably also using the Context: https://typer.tiangolo.com/tutorial/commands/context/

@Leletir if that answers your question, you can close this issue. :heavy_check_mark:

**Comment by Leletir** [comment]
Thank you for your answer, actually it does.

**Comment by larsrinn** [comment]
@tiangolo Indeed, I just tested it using a callback and it works (while scrolling through the documentation I just saw callbacks for options and considered this was unsuitable).

For the rather simple application I'm building this solution is fine. But I guess this might get out of hand for more complex stuff, where multiple groups of commands require different setups. Also closing the connection the connection is not that clean now. So I think `typer` could benefit from a dependency injection system similar to pytest fixtures.

**Comment by dbalabka** [comment]
@tiangolo I'm still wondering why not decouple DI component from FastAPI as a separate package and reuse in both Typer and FastAPI?
I'm currently, building application which has API and CLI interfaces. IMO it is odd that FastAPI has DI implementation but Typer does not. Of course, I can reuse DI from FastAPI, but it does not cover the case when I want only CLI.

**Comment by dbalabka** [comment]
@tiangolo seems it is impossible to reuse FastAPI DI for Typer because of the following error:
```
File ".../typer/main.py", line 586, in get_click_type
    raise RuntimeError(f"Type not yet supported: {annotation}")  # pragma no cover
RuntimeError: Type not yet supported:
```

**Comment by dbalabka** [comment]
To resolve this issue I rid off of using FastAPI DI and install https://github.com/ivankorobkov/python-inject to share same DI container between CLI and API. 
Currently, it is the only way how to avoid code duplication.

@tiangolo I suggest reviewing `python-inject` as a replacement for FastAPI DI.

**Comment by tiangolo** [comment]
The thing is that FastAPI uses the dependency injection system to extract metadata for validation and documentation to be taken from the request.

A dependency function for FastAPI would probably not work for a CLI as it would probably be taking data from a request, e.g. from the body and from cookies. Where would that data come from in the CLI? So, in Typer, there wouldn't be a way to extract that info, so the dependency function would have to be different. And in that case, what benefit would it provide that is not achieved by calling the helper function directly?

**Comment by dbalabka** [comment]
> Where would that data come from in the CLI?

There is a difference between CLI and HTTP input data structures. Still, both have a need to work with some particular dependencies (e.g. services that contain exact logic that can be shared between CLI and HTTP)

>  So, in Typer, there wouldn't be a way to extract that info, so the dependency function would have to be different.

IMO there should not be a difference between DI module in Typer and FastAPI that why I propose to decouple this part of functionality into a separate package or reuse already existing library.

> And in that case, what benefit would it provide that is not achieved by calling the helper function directly?

You probably right. I do not remember have I tried this approach or not. The described error wasn't the only reason why I have migrated to https://github.com/ivankorobkov/python-inject . Unfortunately, with FastAPI DI I have to describe all dependencies manually which isn't productive. I was looking for a library that solves DI task using auto wiring approach which utilizes already existing types hints.

**Comment by tiangolo** [comment]
Ah, yeah, I had seen that style of DI, and that's probably the most traditional way of doing it. But I didn't want to do it that way, as that means there's only one possible provider for a dependency.

So, it was not possible to declare `user: User = Depends(valid_user)` and then somewhere else `user: User = Depends(valid_admin_user)`, because `User` would be provided only by one thing.

And also it would mean that dependencies would have to have some specific shape and interface, or quite some extra concepts and API to learn to register providers (including their terminology). So I ended up deciding on the current style.

But I'm glad you found something that suits your needs :heavy_check_mark: :nerd_face:

**Comment by dbalabka** [comment]
> So, it was not possible to declare user: User = Depends(valid_user) and then somewhere else user: User = Depends(valid_admin_user), because User would be provided only by one thing.

Multiple instances of a single class (e.g., multiple HTTP clients with different endpoint configurations) is common. More often you can face with dependencies on an interface or some more abstract type due to SOLID principles. Complete DI solutions (e.g., Symfony (PHP), Spring (Java)) give the possibility to declared named dependencies instead of type-based. 
Autowiring usually complements named based dependencies declarations. Unfortunately, https://github.com/ivankorobkov/python-inject isn't a complete solution but you always able to declare a [new type](https://docs.python.org/3/library/typing.html#newtype) which is not preferable but solve the issue.

> And also it would mean that dependencies would have to have some specific shape and interface, or quite some extra concepts and API to learn to register providers (including their terminology). So I ended up deciding on the current style.

Autowiring usually minimizes the amount of boilerplate code and have a less steep learning curve.

**Comment by takeda** [comment]
@tiangolo I have somewhat related but slightly different question. Is there a way to create an object at the beginning of the lifecycle of a command and terminate at the end?

For example I want to create aiohttp session and use it in various callbacks and the final command and after completion cleanly close it.

Ideally if this could be done in a form of:

```python
async with aiohttp.ClientSession() as session:
    yield session
```

It would be perfect. Right now I placed async with whenever I need it, but that means there's a separate session for every callback, and this code is being repeated over and over.

**Comment by maldoinc** [comment]
I came across this as I was looking how to do DI in Typer. 

You can use Wireup to share the service layer of the app/api and cli: https://github.com/maldoinc/wireup

```python
# services/some_service.py
@service
class SomeService:
    ...
```

```python
# cli.py
from wireup import container, initialize_container

cli = typer.Typer()

@cli.command()
def create_post(title: str, contents: str) -> None:
    # Using container.get(T) returns an instance of that type.
    svc = container.get(SomeService)



if __name__ == "__main__":
    initialize_container(container, service_modules=[services], parameters=get_config())
    cli()
```

See: https://github.com/maldoinc/wireup?tab=readme-ov-file#share-service-layer-betwen-appapi-and-cli for more examples.
