### ISSUE TITLE
[BUG] Typer.style fails in Windows Powershell with colorama installed

### ISSUE THREAD

**Issue by Fronkan** [tiangolo/typer#84]
### Describe the bug
I tried to print red text in powershell on Windows. However, it just  printed with escape symbols instead. This is with colorama installed and if i manually initialize colorama the colors works as it should.

### To Reproduce

Reporduce non-working version:
```Python
import typer
def main():
    print(typer.style("RED", fg=typer.colors.RED))
if __name__ == "__main__":
    typer.run(main)
```
Outputs:
```
[31mRED[0m
```

With manual colorma init:
```Python
import typer
import colorama
colorama.init()
def main():
    print(typer.style("RED", fg=typer.colors.RED))
if __name__ == "__main__":
    typer.run(main)
```
Ouputs, in red text:
```
RED
```

### Expected behavior
As it in the documentation, https://typer.tiangolo.com/tutorial/printing/#color,  is stated that you don't have to manually initialize colorama I expected the first to work.

### Environment

* OS: Windows
* Typer Version: 0.1.1
* Python version: 3.7.2

**Comment by tiangolo** [comment]
So, for all the Colorama Windows magic to work you have to use `typer.echo()` instead of `print()`, like:

```Python
import typer
def main():
    typer.echo(typer.style("RED", fg=typer.colors.RED))
if __name__ == "__main__":
    typer.run(main)
```

**Comment by Fronkan** [comment]
Thank you! I must haves missed this.
