### ISSUE TITLE
[FEATURE] Explicitly using typer.models.Required

### ISSUE THREAD

**Issue by notpushkin** [tiangolo/typer#87]
### Is your feature request related to a problem

First of all, thank you so much for yet another awesome project! It feels almost like magic to use your products.

However, some things are a bit too magic for me. One is the use of `...` for indication of required parameters. I've found that `typer.models.Required` can be used instead, which feels more explicit and can be understood even without looking at the docs. Do you plan to keep it available in this module? Can I rely on it?

### The solution you would like

Ideally, promote it to `typer.Required` and mention in the docs :)

**Comment by tiangolo** [comment]
I'm glad you're liking it!

I prefer to keep the canonical form of `...` as the main and suggested form in the docs, to keep it in line with FastAPI and Pydantic.

I currently don't have intentions to remove or move that `Required` from there, but still, if you pin your package adequately to the version of Typer that works for you and upgrade only after running the tests, you should be safe to use it. :heavy_check_mark:
