### ISSUE TITLE
Using typer as package with pydantic BaseSettings

### ISSUE THREAD

**Issue by mr-bjerre** [tiangolo/typer#91]
### Describe the bug

I am using `typer` as a package where I get the following error

```python
  .
  .
  File "/root/typer_app/main.py", line 9, in publish
    class Settings(BaseSettings):
  File "pydantic/main.py", line 184, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 136, in pydantic.typing.resolve_annotations
    if arg is None:
KeyError: 'typer_app.main'
```

### To Reproduce

I am using `typer` as a package

```
/root
| typer_app
  | __init__.py
  | main.py
```
where 

 `main.py`
```python
import typer
from pydantic import BaseSettings

app = typer.Typer()


@app.command()
def publish():
    class Settings(BaseSettings):
        HTTP_ENDPOINT: str

    settings = Settings()
    typer.echo(settings.HTTP_ENDPOINT)

```

* Call it with:

```bash
PYTHONPATH=/root typer typer_app.main run
```

* It outputs:

```python
  .
  .
  File "/root/typer_app/main.py", line 9, in publish
    class Settings(BaseSettings):
  File "pydantic/main.py", line 184, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 136, in pydantic.typing.resolve_annotations
    if arg is None:
KeyError: 'typer_app.main'
```

* But I expected it to output a validation error since HTTP_ENDPOINT is not set.

### Environment

```bash
Linux Mint - Python 3.8.2
typer==0.1.1
typer-cli==0.0.8
```

**Comment by mr-bjerre** [comment]
If I instead use `main.py` as a module, i.e. `python main.py` then it works fine

**Comment by tiangolo** [comment]
Yep. I was able to reproduce it with Typer CLI. I think it has to do with the way Pydantic solves global types, and the tricks that Typer CLI does to "inject" the current module live more or less magically...

It is actually an issue with Typer CLI, not with Typer.

Meanwhile, you can solve it by creating a file `__main__.py` in the same package, with:

```Python
from .main import app
app()
```

And calling it with:

```console
$ PYTHONPATH=./ HTTP_ENDPOINT=asdf python -m typer_app
asdf
```

**Comment by asteven** [comment]
JFYI: Related issue (I think) with fix/workaround https://github.com/nolar/kopf/issues/631

**Comment by tiangolo** [comment]
As this is an issue in Typer-CLI and not in Typer, I'm gonna close this one here.

The issue and conversation about Typer-CLI is here: https://github.com/tiangolo/typer-cli/issues/10
