### ISSUE TITLE
[FEATURE] Support datetime.date in addition to datetime.datetime

### ISSUE THREAD

**Issue by lbjarre** [tiangolo/typer#94]
### Is your feature request related to a problem

Typer currently allows for `datetime.datetime`-objects as arguments,
but does not support the less specific `datetime.date`-object:
```python
# example.py
import datetine
import typer

def do_thing_with_date(date: datetime.date):
    typer.echo(f"Year is: {date.year}")

if __name__ == "__main__":
    typer.run(do_thing_with_date)

```
This code produces:
```shell
$ python example.py 2020-04-01
Traceback (most recent call last):
  File "dateapp.py", line 12, in <module>
    typer.run(do_thing_with_date)
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 743, in run
    app()
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 215, in __call__
    return get_command(self)()
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 241, in get_command
    click_command = get_command_from_info(typer_instance.registered_commands[0])
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 423, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 404, in get_params_convertors_ctx_param_name_from_function
    click_param, convertor = get_click_param(param)
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 655, in get_click_param
    parameter_type = get_click_type(
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 586, in get_click_type
    raise RuntimeError(f"Type not yet supported: {annotation}")  # pragma no cover
RuntimeError: Type not yet supported: <class 'datetime.date'>
```

### The solution you would like

Allow for `datetime.date` as input arguments/options to Typer.

### Describe alternatives you've considered

It is true that it is possible to get just the date from `datetime.datetime` in the current implementation:
- input parsing supports the format `%Y-%m-%d` without needing to specify a time
- you can get a `datetime.date`-object with `.date()`

However, I think that allowing for just the date part is better in some situations:
- No need to explicitly extract the date part with `.date()`
- It provides some intention to the end user that only the date part is considered
- It does not confuse any user with input formatting info that is irrelevant to the application: the current error message for missing arg/invalid value for `datetime.datetime` shows the format `"[%Y-%m-%d|%Y-%m-%dT%H:%M:%S|%Y-%m-%d %H:%M:%S]"`

**Comment by tiangolo** [comment]
Hey @lbjarre !

So, as you mention, you can actually use `datetime` and pass just a date with year, month, and day.

The problem is that the data type is implemented in Click, not in Typer, and implementing support for that specific use case would probably involve a lot of extra custom code in Typer itself.

Nevertheless, you can specify your own format, like:

```Python
from datetime import datetime
import typer


def main(date: datetime = typer.Argument(..., formats=["%Y-%m-%d"])):
    typer.echo(f"Year is: {date.year}")


if __name__ == "__main__":
    typer.run(main)
```

**Comment by NikosAlexandris** [comment]
> Nevertheless, you can specify your own format, like:
> 
> ```python
> from datetime import datetime
> import typer
> 
> 
> def main(date: datetime = typer.Argument(..., formats=["%Y-%m-%d"])):
>     typer.echo(f"Year is: {date.year}")
> 
> 
> if __name__ == "__main__":
>     typer.run(main)
> ```

This does not play nice with [xarray's time indexing](https://docs.xarray.dev/en/stable/user-guide/time-series.html#datetime-indexing) for example. An input like `2023-05` should be kept like that : `2023-05` to retrieve this slice of data. For example :

``` python
ds.sel(time="2000-01")
Out[10]: 
<xarray.Dataset>
Dimensions:  (time: 744)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 ... 2000-01-31T23:00:00
Data variables:
    foo      (time) int64 0 1 2 3 4 5 6 7 8 ... 736 737 738 739 740 741 742 743
```

Instead, the following :

``` python
time: Annotated[Optional[datetime], typer.Argument(
            formats=["%Y", "%Y-%m", "%Y-%m-%d", "%Y-%m-%d %H", "%Y-%m-%d %H:%M", "%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H", "%Y-%m-%dT%H:%M", "%Y-%m-%dT%H:%M:%S", ],
```
will return, depending on input, always the first day and first month, even if not given :-/.
For example :
- `2023` in the command line will be converted to 'time': datetime.datetime(2023, 1, 1, 0, 0),
- `2023-05` in the command line will be converte to 'time': datetime.datetime(2023, 5, 1, 0, 0),
-  and so on

Trying to handle all cases manually is too much work, right?  Any ideas?
