### ISSUE TITLE
[FEATURE] Don't prompt if given extra argument

### ISSUE THREAD

**Issue by MrGreenTea** [tiangolo/typer#95]
When using `typer.Option(prompt=True))` and calling the script with more arguments than are allowed, the user will first be prompted for all prompts and then get an error because of the extra argument.

To reproduce use this

```python
# test.py
import typer

app = typer.Typer()

@app.command()
def run(a: str = typer.Option(..., prompt=True)): ...

app()
```

```
❯ python test.py extra
A:
```

but then

```
❯ python test.py extra
A: a
Usage: test.py [OPTIONS]
Try 'test.py --help' for help.

Error: Got unexpected extra argument (extra)
```

This is a weird user experience and should be changed to show the error before prompting if we know we're going to fail anyway.

I hope I could make it understandable what I mean.
Kindest regards and thanks for your great work!

**Comment by tiangolo** [comment]
Could you check with a pure Click alternative? That would let us know if this is a problem in Typer or in Click.

**Comment by MrGreenTea** [comment]
@tiangolo It's the same in `click`:

```py
import click

@click.command()
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(name):
    click.echo(name)


if __name__ == '__main__':
    hello()
```
This provides this output:

```
(click-prompting) MrGreenTea@Desktop:~/development/click-prompting$ python hello.py test
Your name: hello
Usage: hello.py [OPTIONS]
Try 'hello.py --help' for help.

Error: Got unexpected extra argument (test)
```

I found this in the click repository:
https://github.com/pallets/click/issues/1369
