### ISSUE TITLE
[BUG] typer.main.get_group should return a click.Group

### ISSUE THREAD

**Issue by dbanty** [tiangolo/typer#96]
### Describe the bug

The function `typer.main.get_group` is annotated as returning a `click.Command` which isn't _wrong_ because a `click.Group` is a `click.Command`, but means I have to cast to group when trying to integrate with existing Click applications.

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

* Create a file `main.py` with:

```Python
import typer

app = typer.Typer()


@app.callback()
def callback():
    """ My partially-upgraded-to-Typer app """

# insert some fancy new Typer commands here


click_group = typer.main.get_group(app)


@click_group.command()
def some_old_click_function():
      """ I need to rewrite this somday """

```

Run mypy on this script with `mypy main.py` and it will output something like 
> main.py:16: error: "Command" has no attribute "command"

### Expected behavior

Able to drop in Typer at the top level to start slowly converting an existing Click app.

### Environment

* OS: macOS
* Typer Version: 0.2.1
* Python version: 3.8.2
* mypy version: 0.770

**Comment by mdaj06** [comment]
@tiangolo could i take this up?

**Comment by tiangolo** [comment]
Thank you! This should be solved in https://github.com/tiangolo/typer/pull/430 , and will be available in the next release. :nerd_face:
